
// <auto-generated>
//  Bu dosya T4 tarafından üretildi (Services.AllGibEntities.Generated.tt).
//  Elle düzenlemeyin; değişiklikleri .tt içinde yapın ve kaydedin.
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using TurkSoft.Entities.GIBEntityDB;
using TurkSoft.Service.Interface.Gib;
using TurkSoft.Service.Manager.Gib;

namespace TurkSoft.Service.Interface.Gib
{
    /// <summary> Address varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibAddressService : IEntityGibService<Address, long> { }
    /// <summary> Announcement varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibAnnouncementService : IEntityGibService<Announcement, long> { }
    /// <summary> Bank varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibBankService : IEntityGibService<Bank, long> { }
    /// <summary> Brand varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibBrandService : IEntityGibService<Brand, long> { }
    /// <summary> Category varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibCategoryService : IEntityGibService<Category, long> { }
    /// <summary> City varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibCityService : IEntityGibService<City, long> { }
    /// <summary> CommissionsMove varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibCommissionsMoveService : IEntityGibService<CommissionsMove, long> { }
    /// <summary> Country varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibCountryService : IEntityGibService<Country, long> { }
    /// <summary> Currency varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibCurrencyService : IEntityGibService<Currency, long> { }
    /// <summary> Customer varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibCustomerService : IEntityGibService<Customer, long> { }
    /// <summary> CustomersGroup varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibCustomersGroupService : IEntityGibService<CustomersGroup, long> { }
    /// <summary> CustomReport varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibCustomReportService : IEntityGibService<CustomReport, long> { }
    /// <summary> Dealer varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibDealerService : IEntityGibService<Dealer, long> { }
    /// <summary> Document varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibDocumentService : IEntityGibService<Document, long> { }
    /// <summary> DocumentType varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibDocumentTypeService : IEntityGibService<DocumentType, long> { }
    /// <summary> ExchangeRate varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibExchangeRateService : IEntityGibService<ExchangeRate, long> { }
    /// <summary> ExchangeRates varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibExchangeRatesService : IEntityGibService<ExchangeRates, long> { }
    /// <summary> GeneralReport varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibGeneralReportService : IEntityGibService<GeneralReport, long> { }
    /// <summary> Group varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibGroupService : IEntityGibService<Group, long> { }
    /// <summary> Identifiers varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibIdentifiersService : IEntityGibService<Identifiers, long> { }
    /// <summary> InfCode varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibInfCodeService : IEntityGibService<InfCode, long> { }
    /// <summary> Invoice varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibInvoiceService : IEntityGibService<Invoice, long> { }
    /// <summary> InvoicesDiscount varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibInvoicesDiscountService : IEntityGibService<InvoicesDiscount, long> { }
    /// <summary> InvoicesItem varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibInvoicesItemService : IEntityGibService<InvoicesItem, long> { }
    /// <summary> InvoicesPayment varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibInvoicesPaymentService : IEntityGibService<InvoicesPayment, long> { }
    /// <summary> InvoicesTax varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibInvoicesTaxService : IEntityGibService<InvoicesTax, long> { }
    /// <summary> Item varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibItemService : IEntityGibService<Item, long> { }
    /// <summary> ItemsCategory varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibItemsCategoryService : IEntityGibService<ItemsCategory, long> { }
    /// <summary> ItemsDiscount varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibItemsDiscountService : IEntityGibService<ItemsDiscount, long> { }
    /// <summary> ItemsExport varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibItemsExportService : IEntityGibService<ItemsExport, long> { }
    /// <summary> Log varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibLogService : IEntityGibService<Log, long> { }
    /// <summary> Payment varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibPaymentService : IEntityGibService<Payment, long> { }
    /// <summary> PaymentAccount varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibPaymentAccountService : IEntityGibService<PaymentAccount, long> { }
    /// <summary> PaymentType varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibPaymentTypeService : IEntityGibService<PaymentType, long> { }
    /// <summary> Permission varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibPermissionService : IEntityGibService<Permission, long> { }
    /// <summary> ProcesingReport varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibProcesingReportService : IEntityGibService<ProcesingReport, long> { }
    /// <summary> Purchase varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibPurchaseService : IEntityGibService<Purchase, long> { }
    /// <summary> PurchaseItem varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibPurchaseItemService : IEntityGibService<PurchaseItem, long> { }
    /// <summary> Request varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibRequestService : IEntityGibService<Request, long> { }
    /// <summary> Returns varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibReturnsService : IEntityGibService<Returns, long> { }
    /// <summary> Role varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibRoleService : IEntityGibService<Role, long> { }
    /// <summary> RolePermission varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibRolePermissionService : IEntityGibService<RolePermission, long> { }
    /// <summary> ServicesProvider varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibServicesProviderService : IEntityGibService<ServicesProvider, long> { }
    /// <summary> Setting varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibSettingService : IEntityGibService<Setting, long> { }
    /// <summary> Sgk varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibSgkService : IEntityGibService<Sgk, long> { }
    /// <summary> Stock varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibStockService : IEntityGibService<Stock, long> { }
    /// <summary> StockMovement varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibStockMovementService : IEntityGibService<StockMovement, long> { }
    /// <summary> Supplier varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibSupplierService : IEntityGibService<Supplier, long> { }
    /// <summary> Tax varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibTaxService : IEntityGibService<Tax, long> { }
    /// <summary> Tourist varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibTouristService : IEntityGibService<Tourist, long> { }
    /// <summary> Unit varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibUnitService : IEntityGibService<Unit, long> { }
    /// <summary> User varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibUserService : IEntityGibService<User, long> { }
    /// <summary> UserAnnouncementRead varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibUserAnnouncementReadService : IEntityGibService<UserAnnouncementRead, long> { }
    /// <summary> UserRole varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibUserRoleService : IEntityGibService<UserRole, long> { }
    /// <summary> Users varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibUsersService : IEntityGibService<Users, long> { }
    /// <summary> Warehouse varlığı için GIB servis sözleşmesi. </summary>
    public partial interface IGibWarehouseService : IEntityGibService<Warehouse, long> { }
}

namespace TurkSoft.Service.Manager.Gib
{
    /// <summary> Address varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibAddressManager : EntityGibManager<Address, long>, TurkSoft.Service.Interface.Gib.IGibAddressService
    {
        public GibAddressManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Announcement varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibAnnouncementManager : EntityGibManager<Announcement, long>, TurkSoft.Service.Interface.Gib.IGibAnnouncementService
    {
        public GibAnnouncementManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Bank varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibBankManager : EntityGibManager<Bank, long>, TurkSoft.Service.Interface.Gib.IGibBankService
    {
        public GibBankManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Brand varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibBrandManager : EntityGibManager<Brand, long>, TurkSoft.Service.Interface.Gib.IGibBrandService
    {
        public GibBrandManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Category varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibCategoryManager : EntityGibManager<Category, long>, TurkSoft.Service.Interface.Gib.IGibCategoryService
    {
        public GibCategoryManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> City varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibCityManager : EntityGibManager<City, long>, TurkSoft.Service.Interface.Gib.IGibCityService
    {
        public GibCityManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> CommissionsMove varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibCommissionsMoveManager : EntityGibManager<CommissionsMove, long>, TurkSoft.Service.Interface.Gib.IGibCommissionsMoveService
    {
        public GibCommissionsMoveManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Country varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibCountryManager : EntityGibManager<Country, long>, TurkSoft.Service.Interface.Gib.IGibCountryService
    {
        public GibCountryManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Currency varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibCurrencyManager : EntityGibManager<Currency, long>, TurkSoft.Service.Interface.Gib.IGibCurrencyService
    {
        public GibCurrencyManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Customer varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibCustomerManager : EntityGibManager<Customer, long>, TurkSoft.Service.Interface.Gib.IGibCustomerService
    {
        public GibCustomerManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> CustomersGroup varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibCustomersGroupManager : EntityGibManager<CustomersGroup, long>, TurkSoft.Service.Interface.Gib.IGibCustomersGroupService
    {
        public GibCustomersGroupManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> CustomReport varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibCustomReportManager : EntityGibManager<CustomReport, long>, TurkSoft.Service.Interface.Gib.IGibCustomReportService
    {
        public GibCustomReportManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Dealer varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibDealerManager : EntityGibManager<Dealer, long>, TurkSoft.Service.Interface.Gib.IGibDealerService
    {
        public GibDealerManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Document varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibDocumentManager : EntityGibManager<Document, long>, TurkSoft.Service.Interface.Gib.IGibDocumentService
    {
        public GibDocumentManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> DocumentType varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibDocumentTypeManager : EntityGibManager<DocumentType, long>, TurkSoft.Service.Interface.Gib.IGibDocumentTypeService
    {
        public GibDocumentTypeManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> ExchangeRate varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibExchangeRateManager : EntityGibManager<ExchangeRate, long>, TurkSoft.Service.Interface.Gib.IGibExchangeRateService
    {
        public GibExchangeRateManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> ExchangeRates varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibExchangeRatesManager : EntityGibManager<ExchangeRates, long>, TurkSoft.Service.Interface.Gib.IGibExchangeRatesService
    {
        public GibExchangeRatesManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> GeneralReport varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibGeneralReportManager : EntityGibManager<GeneralReport, long>, TurkSoft.Service.Interface.Gib.IGibGeneralReportService
    {
        public GibGeneralReportManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Group varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibGroupManager : EntityGibManager<Group, long>, TurkSoft.Service.Interface.Gib.IGibGroupService
    {
        public GibGroupManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Identifiers varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibIdentifiersManager : EntityGibManager<Identifiers, long>, TurkSoft.Service.Interface.Gib.IGibIdentifiersService
    {
        public GibIdentifiersManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> InfCode varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibInfCodeManager : EntityGibManager<InfCode, long>, TurkSoft.Service.Interface.Gib.IGibInfCodeService
    {
        public GibInfCodeManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Invoice varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibInvoiceManager : EntityGibManager<Invoice, long>, TurkSoft.Service.Interface.Gib.IGibInvoiceService
    {
        public GibInvoiceManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> InvoicesDiscount varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibInvoicesDiscountManager : EntityGibManager<InvoicesDiscount, long>, TurkSoft.Service.Interface.Gib.IGibInvoicesDiscountService
    {
        public GibInvoicesDiscountManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> InvoicesItem varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibInvoicesItemManager : EntityGibManager<InvoicesItem, long>, TurkSoft.Service.Interface.Gib.IGibInvoicesItemService
    {
        public GibInvoicesItemManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> InvoicesPayment varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibInvoicesPaymentManager : EntityGibManager<InvoicesPayment, long>, TurkSoft.Service.Interface.Gib.IGibInvoicesPaymentService
    {
        public GibInvoicesPaymentManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> InvoicesTax varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibInvoicesTaxManager : EntityGibManager<InvoicesTax, long>, TurkSoft.Service.Interface.Gib.IGibInvoicesTaxService
    {
        public GibInvoicesTaxManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Item varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibItemManager : EntityGibManager<Item, long>, TurkSoft.Service.Interface.Gib.IGibItemService
    {
        public GibItemManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> ItemsCategory varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibItemsCategoryManager : EntityGibManager<ItemsCategory, long>, TurkSoft.Service.Interface.Gib.IGibItemsCategoryService
    {
        public GibItemsCategoryManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> ItemsDiscount varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibItemsDiscountManager : EntityGibManager<ItemsDiscount, long>, TurkSoft.Service.Interface.Gib.IGibItemsDiscountService
    {
        public GibItemsDiscountManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> ItemsExport varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibItemsExportManager : EntityGibManager<ItemsExport, long>, TurkSoft.Service.Interface.Gib.IGibItemsExportService
    {
        public GibItemsExportManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Log varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibLogManager : EntityGibManager<Log, long>, TurkSoft.Service.Interface.Gib.IGibLogService
    {
        public GibLogManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Payment varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibPaymentManager : EntityGibManager<Payment, long>, TurkSoft.Service.Interface.Gib.IGibPaymentService
    {
        public GibPaymentManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> PaymentAccount varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibPaymentAccountManager : EntityGibManager<PaymentAccount, long>, TurkSoft.Service.Interface.Gib.IGibPaymentAccountService
    {
        public GibPaymentAccountManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> PaymentType varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibPaymentTypeManager : EntityGibManager<PaymentType, long>, TurkSoft.Service.Interface.Gib.IGibPaymentTypeService
    {
        public GibPaymentTypeManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Permission varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibPermissionManager : EntityGibManager<Permission, long>, TurkSoft.Service.Interface.Gib.IGibPermissionService
    {
        public GibPermissionManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> ProcesingReport varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibProcesingReportManager : EntityGibManager<ProcesingReport, long>, TurkSoft.Service.Interface.Gib.IGibProcesingReportService
    {
        public GibProcesingReportManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Purchase varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibPurchaseManager : EntityGibManager<Purchase, long>, TurkSoft.Service.Interface.Gib.IGibPurchaseService
    {
        public GibPurchaseManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> PurchaseItem varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibPurchaseItemManager : EntityGibManager<PurchaseItem, long>, TurkSoft.Service.Interface.Gib.IGibPurchaseItemService
    {
        public GibPurchaseItemManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Request varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibRequestManager : EntityGibManager<Request, long>, TurkSoft.Service.Interface.Gib.IGibRequestService
    {
        public GibRequestManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Returns varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibReturnsManager : EntityGibManager<Returns, long>, TurkSoft.Service.Interface.Gib.IGibReturnsService
    {
        public GibReturnsManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Role varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibRoleManager : EntityGibManager<Role, long>, TurkSoft.Service.Interface.Gib.IGibRoleService
    {
        public GibRoleManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> RolePermission varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibRolePermissionManager : EntityGibManager<RolePermission, long>, TurkSoft.Service.Interface.Gib.IGibRolePermissionService
    {
        public GibRolePermissionManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> ServicesProvider varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibServicesProviderManager : EntityGibManager<ServicesProvider, long>, TurkSoft.Service.Interface.Gib.IGibServicesProviderService
    {
        public GibServicesProviderManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Setting varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibSettingManager : EntityGibManager<Setting, long>, TurkSoft.Service.Interface.Gib.IGibSettingService
    {
        public GibSettingManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Sgk varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibSgkManager : EntityGibManager<Sgk, long>, TurkSoft.Service.Interface.Gib.IGibSgkService
    {
        public GibSgkManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Stock varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibStockManager : EntityGibManager<Stock, long>, TurkSoft.Service.Interface.Gib.IGibStockService
    {
        public GibStockManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> StockMovement varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibStockMovementManager : EntityGibManager<StockMovement, long>, TurkSoft.Service.Interface.Gib.IGibStockMovementService
    {
        public GibStockMovementManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Supplier varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibSupplierManager : EntityGibManager<Supplier, long>, TurkSoft.Service.Interface.Gib.IGibSupplierService
    {
        public GibSupplierManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Tax varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibTaxManager : EntityGibManager<Tax, long>, TurkSoft.Service.Interface.Gib.IGibTaxService
    {
        public GibTaxManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Tourist varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibTouristManager : EntityGibManager<Tourist, long>, TurkSoft.Service.Interface.Gib.IGibTouristService
    {
        public GibTouristManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Unit varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibUnitManager : EntityGibManager<Unit, long>, TurkSoft.Service.Interface.Gib.IGibUnitService
    {
        public GibUnitManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> User varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibUserManager : EntityGibManager<User, long>, TurkSoft.Service.Interface.Gib.IGibUserService
    {
        public GibUserManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> UserAnnouncementRead varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibUserAnnouncementReadManager : EntityGibManager<UserAnnouncementRead, long>, TurkSoft.Service.Interface.Gib.IGibUserAnnouncementReadService
    {
        public GibUserAnnouncementReadManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> UserRole varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibUserRoleManager : EntityGibManager<UserRole, long>, TurkSoft.Service.Interface.Gib.IGibUserRoleService
    {
        public GibUserRoleManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Users varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibUsersManager : EntityGibManager<Users, long>, TurkSoft.Service.Interface.Gib.IGibUsersService
    {
        public GibUsersManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
    /// <summary> Warehouse varlığı için GIB servis implementasyonu (iş katmanı). </summary>
    public partial class GibWarehouseManager : EntityGibManager<Warehouse, long>, TurkSoft.Service.Interface.Gib.IGibWarehouseService
    {
        public GibWarehouseManager(GibAppDbContext db) : base(db)
        {
            OnConstructed();
        }

        /// <summary> İsteğe bağlı constructor sonrası kanca. </summary>
        partial void OnConstructed();
    }
}
