//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VakıfKatilimSrv
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModelBase", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Base")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.ResponseModelBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.ResponseModelBaseOfArrayOfCustomerTransactionResponseModel_P6CyoERI))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.CustomerTransactionResponseModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.CustomerTransactionDetailResponseModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.ResponseModelBaseOfArrayOfCustomerTransactionDetailResponseModel_P6CyoERI))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.ResponseModelBaseOfAccountBalanceResponseModel_P6CyoERI))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.AccountBalanceResponseModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.ResponseModelBaseOfArrayOfAccountListResponseModel_P6CyoERI))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.AccountListResponseModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.ResponseModelBaseOfCustomerTransactionSlipDataResponseModel_P6CyoERI))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.CustomerTransactionSlipDataResponseModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.RequestModelBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.AccountBalanceRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.AccountListRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.CustomerTransactionRequest))]
    public partial class ModelBase : object
    {
        
        private string EncryptedValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EncryptedValue
        {
            get
            {
                return this.EncryptedValueField;
            }
            set
            {
                this.EncryptedValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseModelBase", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Base")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.ResponseModelBaseOfArrayOfCustomerTransactionResponseModel_P6CyoERI))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.CustomerTransactionResponseModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.CustomerTransactionDetailResponseModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.ResponseModelBaseOfArrayOfCustomerTransactionDetailResponseModel_P6CyoERI))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.ResponseModelBaseOfAccountBalanceResponseModel_P6CyoERI))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.AccountBalanceResponseModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.ResponseModelBaseOfArrayOfAccountListResponseModel_P6CyoERI))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.AccountListResponseModel))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.ResponseModelBaseOfCustomerTransactionSlipDataResponseModel_P6CyoERI))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.CustomerTransactionSlipDataResponseModel))]
    public partial class ResponseModelBase : VakıfKatilimSrv.ModelBase
    {
        
        private VakıfKatilimSrv.Result[] ResultsField;
        
        private bool ShowMobilePopupField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public VakıfKatilimSrv.Result[] Results
        {
            get
            {
                return this.ResultsField;
            }
            set
            {
                this.ResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool ShowMobilePopup
        {
            get
            {
                return this.ShowMobilePopupField;
            }
            set
            {
                this.ShowMobilePopupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseModelBaseOfArrayOfCustomerTransactionResponseModel_P6CyoERI", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Base")]
    public partial class ResponseModelBaseOfArrayOfCustomerTransactionResponseModel_P6CyoERI : VakıfKatilimSrv.ResponseModelBase
    {
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private VakıfKatilimSrv.CustomerTransactionResponseModel[] ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public VakıfKatilimSrv.CustomerTransactionResponseModel[] Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerTransactionResponseModel", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CustomerTransaction" +
        "")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.CustomerTransactionDetailResponseModel))]
    public partial class CustomerTransactionResponseModel : VakıfKatilimSrv.ResponseModelBase
    {
        
        private decimal AmountField;
        
        private System.Nullable<decimal> BalanceField;
        
        private decimal BusinessKeyField;
        
        private int ChannelIdField;
        
        private string CommentField;
        
        private short FECField;
        
        private string FECNameField;
        
        private System.DateTime SystemDateField;
        
        private short TranBranchIdField;
        
        private string TranBranchNameField;
        
        private System.DateTime TranDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<decimal> Balance
        {
            get
            {
                return this.BalanceField;
            }
            set
            {
                this.BalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public decimal BusinessKey
        {
            get
            {
                return this.BusinessKeyField;
            }
            set
            {
                this.BusinessKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int ChannelId
        {
            get
            {
                return this.ChannelIdField;
            }
            set
            {
                this.ChannelIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Comment
        {
            get
            {
                return this.CommentField;
            }
            set
            {
                this.CommentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public short FEC
        {
            get
            {
                return this.FECField;
            }
            set
            {
                this.FECField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FECName
        {
            get
            {
                return this.FECNameField;
            }
            set
            {
                this.FECNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.DateTime SystemDate
        {
            get
            {
                return this.SystemDateField;
            }
            set
            {
                this.SystemDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public short TranBranchId
        {
            get
            {
                return this.TranBranchIdField;
            }
            set
            {
                this.TranBranchIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TranBranchName
        {
            get
            {
                return this.TranBranchNameField;
            }
            set
            {
                this.TranBranchNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.DateTime TranDate
        {
            get
            {
                return this.TranDateField;
            }
            set
            {
                this.TranDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerTransactionDetailResponseModel", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CustomerTransaction" +
        "")]
    public partial class CustomerTransactionDetailResponseModel : VakıfKatilimSrv.CustomerTransactionResponseModel
    {
        
        private System.Nullable<decimal> Balance1Field;
        
        private string DescriptionField;
        
        private System.Nullable<decimal> MainBusinessKeyField;
        
        private System.Nullable<int> QueryTokenField;
        
        private string QueryTokenStrField;
        
        private string ReceiverAccountNumberField;
        
        private string ReceiverBankCodeField;
        
        private string ReceiverBranchCodeField;
        
        private string ReceiverNameField;
        
        private string ReceiverPhoneNumberField;
        
        private string ReceiverTaxNumberField;
        
        private string SenderAccountNumberField;
        
        private string SenderBankCodeField;
        
        private string SenderBranchCodeField;
        
        private string SenderNameField;
        
        private string SenderPhoneNumberField;
        
        private string SenderTaxNumberField;
        
        private short SeqNumField;
        
        private System.Nullable<int> TransactionTypeField;
        
        private string TransactionTypeDescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Balance", EmitDefaultValue=false)]
        public System.Nullable<decimal> Balance1
        {
            get
            {
                return this.Balance1Field;
            }
            set
            {
                this.Balance1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<decimal> MainBusinessKey
        {
            get
            {
                return this.MainBusinessKeyField;
            }
            set
            {
                this.MainBusinessKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> QueryToken
        {
            get
            {
                return this.QueryTokenField;
            }
            set
            {
                this.QueryTokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string QueryTokenStr
        {
            get
            {
                return this.QueryTokenStrField;
            }
            set
            {
                this.QueryTokenStrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReceiverAccountNumber
        {
            get
            {
                return this.ReceiverAccountNumberField;
            }
            set
            {
                this.ReceiverAccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReceiverBankCode
        {
            get
            {
                return this.ReceiverBankCodeField;
            }
            set
            {
                this.ReceiverBankCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReceiverBranchCode
        {
            get
            {
                return this.ReceiverBranchCodeField;
            }
            set
            {
                this.ReceiverBranchCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReceiverName
        {
            get
            {
                return this.ReceiverNameField;
            }
            set
            {
                this.ReceiverNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReceiverPhoneNumber
        {
            get
            {
                return this.ReceiverPhoneNumberField;
            }
            set
            {
                this.ReceiverPhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReceiverTaxNumber
        {
            get
            {
                return this.ReceiverTaxNumberField;
            }
            set
            {
                this.ReceiverTaxNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SenderAccountNumber
        {
            get
            {
                return this.SenderAccountNumberField;
            }
            set
            {
                this.SenderAccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SenderBankCode
        {
            get
            {
                return this.SenderBankCodeField;
            }
            set
            {
                this.SenderBankCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SenderBranchCode
        {
            get
            {
                return this.SenderBranchCodeField;
            }
            set
            {
                this.SenderBranchCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SenderName
        {
            get
            {
                return this.SenderNameField;
            }
            set
            {
                this.SenderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SenderPhoneNumber
        {
            get
            {
                return this.SenderPhoneNumberField;
            }
            set
            {
                this.SenderPhoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SenderTaxNumber
        {
            get
            {
                return this.SenderTaxNumberField;
            }
            set
            {
                this.SenderTaxNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public short SeqNum
        {
            get
            {
                return this.SeqNumField;
            }
            set
            {
                this.SeqNumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> TransactionType
        {
            get
            {
                return this.TransactionTypeField;
            }
            set
            {
                this.TransactionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TransactionTypeDescription
        {
            get
            {
                return this.TransactionTypeDescriptionField;
            }
            set
            {
                this.TransactionTypeDescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseModelBaseOfArrayOfCustomerTransactionDetailResponseModel_P6CyoERI", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Base")]
    public partial class ResponseModelBaseOfArrayOfCustomerTransactionDetailResponseModel_P6CyoERI : VakıfKatilimSrv.ResponseModelBase
    {
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private VakıfKatilimSrv.CustomerTransactionDetailResponseModel[] ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public VakıfKatilimSrv.CustomerTransactionDetailResponseModel[] Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseModelBaseOfAccountBalanceResponseModel_P6CyoERI", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Base")]
    public partial class ResponseModelBaseOfAccountBalanceResponseModel_P6CyoERI : VakıfKatilimSrv.ResponseModelBase
    {
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private VakıfKatilimSrv.AccountBalanceResponseModel ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public VakıfKatilimSrv.AccountBalanceResponseModel Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountBalanceResponseModel", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CustomerTransaction" +
        "")]
    public partial class AccountBalanceResponseModel : VakıfKatilimSrv.ResponseModelBase
    {
        
        private string AccountAliasField;
        
        private int AccountNumberField;
        
        private short AccountSuffixField;
        
        private string AccountTypeField;
        
        private System.Nullable<decimal> BalanceField;
        
        private string BranchNameField;
        
        private System.Nullable<System.DateTime> CloseDateField;
        
        private string CustomerNameField;
        
        private short FECField;
        
        private string FecNameField;
        
        private string IBANField;
        
        private byte IsActiveField;
        
        private System.Nullable<System.DateTime> MaturityEndField;
        
        private System.Nullable<System.DateTime> OpenDateField;
        
        private System.Nullable<decimal> WithHoldingAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccountAlias
        {
            get
            {
                return this.AccountAliasField;
            }
            set
            {
                this.AccountAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public short AccountSuffix
        {
            get
            {
                return this.AccountSuffixField;
            }
            set
            {
                this.AccountSuffixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccountType
        {
            get
            {
                return this.AccountTypeField;
            }
            set
            {
                this.AccountTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<decimal> Balance
        {
            get
            {
                return this.BalanceField;
            }
            set
            {
                this.BalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BranchName
        {
            get
            {
                return this.BranchNameField;
            }
            set
            {
                this.BranchNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> CloseDate
        {
            get
            {
                return this.CloseDateField;
            }
            set
            {
                this.CloseDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CustomerName
        {
            get
            {
                return this.CustomerNameField;
            }
            set
            {
                this.CustomerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public short FEC
        {
            get
            {
                return this.FECField;
            }
            set
            {
                this.FECField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FecName
        {
            get
            {
                return this.FecNameField;
            }
            set
            {
                this.FecNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IBAN
        {
            get
            {
                return this.IBANField;
            }
            set
            {
                this.IBANField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> MaturityEnd
        {
            get
            {
                return this.MaturityEndField;
            }
            set
            {
                this.MaturityEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> OpenDate
        {
            get
            {
                return this.OpenDateField;
            }
            set
            {
                this.OpenDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<decimal> WithHoldingAmount
        {
            get
            {
                return this.WithHoldingAmountField;
            }
            set
            {
                this.WithHoldingAmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseModelBaseOfArrayOfAccountListResponseModel_P6CyoERI", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Base")]
    public partial class ResponseModelBaseOfArrayOfAccountListResponseModel_P6CyoERI : VakıfKatilimSrv.ResponseModelBase
    {
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private VakıfKatilimSrv.AccountListResponseModel[] ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public VakıfKatilimSrv.AccountListResponseModel[] Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountListResponseModel", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CustomerTransaction" +
        "")]
    public partial class AccountListResponseModel : VakıfKatilimSrv.ResponseModelBase
    {
        
        private string AccountAliasField;
        
        private int AccountNumberField;
        
        private short AccountSuffixField;
        
        private System.Nullable<decimal> BalanceField;
        
        private short BranchIdField;
        
        private string BranchNameField;
        
        private System.Nullable<System.DateTime> CloseDateField;
        
        private short FECField;
        
        private string FECNameField;
        
        private string IBANField;
        
        private System.Nullable<short> IsActiveField;
        
        private System.Nullable<System.DateTime> MaturityBeginField;
        
        private System.Nullable<System.DateTime> MaturityEndField;
        
        private System.Nullable<System.DateTime> OpenDateField;
        
        private string ProductNameField;
        
        private short ProductTypeField;
        
        private System.Nullable<decimal> WithHoldingAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AccountAlias
        {
            get
            {
                return this.AccountAliasField;
            }
            set
            {
                this.AccountAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public short AccountSuffix
        {
            get
            {
                return this.AccountSuffixField;
            }
            set
            {
                this.AccountSuffixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<decimal> Balance
        {
            get
            {
                return this.BalanceField;
            }
            set
            {
                this.BalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public short BranchId
        {
            get
            {
                return this.BranchIdField;
            }
            set
            {
                this.BranchIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BranchName
        {
            get
            {
                return this.BranchNameField;
            }
            set
            {
                this.BranchNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> CloseDate
        {
            get
            {
                return this.CloseDateField;
            }
            set
            {
                this.CloseDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public short FEC
        {
            get
            {
                return this.FECField;
            }
            set
            {
                this.FECField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FECName
        {
            get
            {
                return this.FECNameField;
            }
            set
            {
                this.FECNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IBAN
        {
            get
            {
                return this.IBANField;
            }
            set
            {
                this.IBANField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<short> IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> MaturityBegin
        {
            get
            {
                return this.MaturityBeginField;
            }
            set
            {
                this.MaturityBeginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> MaturityEnd
        {
            get
            {
                return this.MaturityEndField;
            }
            set
            {
                this.MaturityEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> OpenDate
        {
            get
            {
                return this.OpenDateField;
            }
            set
            {
                this.OpenDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductName
        {
            get
            {
                return this.ProductNameField;
            }
            set
            {
                this.ProductNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public short ProductType
        {
            get
            {
                return this.ProductTypeField;
            }
            set
            {
                this.ProductTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<decimal> WithHoldingAmount
        {
            get
            {
                return this.WithHoldingAmountField;
            }
            set
            {
                this.WithHoldingAmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseModelBaseOfCustomerTransactionSlipDataResponseModel_P6CyoERI", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Base")]
    public partial class ResponseModelBaseOfCustomerTransactionSlipDataResponseModel_P6CyoERI : VakıfKatilimSrv.ResponseModelBase
    {
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private VakıfKatilimSrv.CustomerTransactionSlipDataResponseModel ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public VakıfKatilimSrv.CustomerTransactionSlipDataResponseModel Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerTransactionSlipDataResponseModel", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CustomerTransaction" +
        "")]
    public partial class CustomerTransactionSlipDataResponseModel : VakıfKatilimSrv.ResponseModelBase
    {
        
        private decimal SlipBusinessKeyField;
        
        private byte[] SlipDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public decimal SlipBusinessKey
        {
            get
            {
                return this.SlipBusinessKeyField;
            }
            set
            {
                this.SlipBusinessKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] SlipData
        {
            get
            {
                return this.SlipDataField;
            }
            set
            {
                this.SlipDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestModelBase", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Base")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.AccountBalanceRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.AccountListRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(VakıfKatilimSrv.CustomerTransactionRequest))]
    public partial class RequestModelBase : VakıfKatilimSrv.ModelBase
    {
        
        private string ExtUNameField;
        
        private string ExtUPasswordField;
        
        private string ExtUSessionKeyField;
        
        private bool IsNewDefinedTransactionField;
        
        private System.Nullable<int> LanguageIdField;
        
        private string MethodNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtUName
        {
            get
            {
                return this.ExtUNameField;
            }
            set
            {
                this.ExtUNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtUPassword
        {
            get
            {
                return this.ExtUPasswordField;
            }
            set
            {
                this.ExtUPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtUSessionKey
        {
            get
            {
                return this.ExtUSessionKeyField;
            }
            set
            {
                this.ExtUSessionKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool IsNewDefinedTransaction
        {
            get
            {
                return this.IsNewDefinedTransactionField;
            }
            set
            {
                this.IsNewDefinedTransactionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> LanguageId
        {
            get
            {
                return this.LanguageIdField;
            }
            set
            {
                this.LanguageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MethodName
        {
            get
            {
                return this.MethodNameField;
            }
            set
            {
                this.MethodNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountBalanceRequest", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CustomerTransaction" +
        "")]
    public partial class AccountBalanceRequest : VakıfKatilimSrv.RequestModelBase
    {
        
        private int AccountNumberField;
        
        private short AccountSuffixField;
        
        private System.DateTime BalanceDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public short AccountSuffix
        {
            get
            {
                return this.AccountSuffixField;
            }
            set
            {
                this.AccountSuffixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.DateTime BalanceDate
        {
            get
            {
                return this.BalanceDateField;
            }
            set
            {
                this.BalanceDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountListRequest", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CustomerTransaction" +
        "")]
    public partial class AccountListRequest : VakıfKatilimSrv.RequestModelBase
    {
        
        private int AccountNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerTransactionRequest", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CustomerTransaction" +
        "")]
    public partial class CustomerTransactionRequest : VakıfKatilimSrv.RequestModelBase
    {
        
        private int AccountNumberField;
        
        private short AccountSuffixField;
        
        private System.DateTime BeginDateField;
        
        private VakıfKatilimSrv.DebitCreditCode DebitCreditCodeField;
        
        private System.DateTime EndDateField;
        
        private bool HasTimeFilterField;
        
        private decimal SlipBusinessKeyField;
        
        private System.Nullable<int> TransactionTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public short AccountSuffix
        {
            get
            {
                return this.AccountSuffixField;
            }
            set
            {
                this.AccountSuffixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.DateTime BeginDate
        {
            get
            {
                return this.BeginDateField;
            }
            set
            {
                this.BeginDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public VakıfKatilimSrv.DebitCreditCode DebitCreditCode
        {
            get
            {
                return this.DebitCreditCodeField;
            }
            set
            {
                this.DebitCreditCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.DateTime EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool HasTimeFilter
        {
            get
            {
                return this.HasTimeFilterField;
            }
            set
            {
                this.HasTimeFilterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public decimal SlipBusinessKey
        {
            get
            {
                return this.SlipBusinessKeyField;
            }
            set
            {
                this.SlipBusinessKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> TransactionType
        {
            get
            {
                return this.TransactionTypeField;
            }
            set
            {
                this.TransactionTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DebitCreditCode", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CustomerTransaction" +
        "")]
    public enum DebitCreditCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Debit = 450,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Credit = 950,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Base")]
    public partial class Result : object
    {
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private string ExceptionField;
        
        private bool IsFriendlyField;
        
        private string[] ParamsField;
        
        private VakıfKatilimSrv.Severity SeverityField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Exception
        {
            get
            {
                return this.ExceptionField;
            }
            set
            {
                this.ExceptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool IsFriendly
        {
            get
            {
                return this.IsFriendlyField;
            }
            set
            {
                this.IsFriendlyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] Params
        {
            get
            {
                return this.ParamsField;
            }
            set
            {
                this.ParamsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public VakıfKatilimSrv.Severity Severity
        {
            get
            {
                return this.SeverityField;
            }
            set
            {
                this.SeverityField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Severity", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Base")]
    public enum Severity : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Information = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://boa.net/BOA.Integration.CustomerTransaction/CustomerTransactionService", ConfigurationName="VakıfKatilimSrv.ICustomerTransactionService")]
    public interface ICustomerTransactionService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://boa.net/BOA.Integration.CustomerTransaction/CustomerTransactionService/ICu" +
            "stomerTransactionService/GetCustomerTransactions", ReplyAction="http://boa.net/BOA.Integration.CustomerTransaction/CustomerTransactionService/ICu" +
            "stomerTransactionService/GetCustomerTransactionsResponse")]
        System.Threading.Tasks.Task<VakıfKatilimSrv.ResponseModelBaseOfArrayOfCustomerTransactionResponseModel_P6CyoERI> GetCustomerTransactionsAsync(VakıfKatilimSrv.CustomerTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://boa.net/BOA.Integration.CustomerTransaction/CustomerTransactionService/ICu" +
            "stomerTransactionService/GetCustomerTransactionDetails", ReplyAction="http://boa.net/BOA.Integration.CustomerTransaction/CustomerTransactionService/ICu" +
            "stomerTransactionService/GetCustomerTransactionDetailsResponse")]
        System.Threading.Tasks.Task<VakıfKatilimSrv.ResponseModelBaseOfArrayOfCustomerTransactionDetailResponseModel_P6CyoERI> GetCustomerTransactionDetailsAsync(VakıfKatilimSrv.CustomerTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://boa.net/BOA.Integration.CustomerTransaction/CustomerTransactionService/ICu" +
            "stomerTransactionService/GetAccountBalance", ReplyAction="http://boa.net/BOA.Integration.CustomerTransaction/CustomerTransactionService/ICu" +
            "stomerTransactionService/GetAccountBalanceResponse")]
        System.Threading.Tasks.Task<VakıfKatilimSrv.ResponseModelBaseOfAccountBalanceResponseModel_P6CyoERI> GetAccountBalanceAsync(VakıfKatilimSrv.AccountBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://boa.net/BOA.Integration.CustomerTransaction/CustomerTransactionService/ICu" +
            "stomerTransactionService/GetAccountList", ReplyAction="http://boa.net/BOA.Integration.CustomerTransaction/CustomerTransactionService/ICu" +
            "stomerTransactionService/GetAccountListResponse")]
        System.Threading.Tasks.Task<VakıfKatilimSrv.ResponseModelBaseOfArrayOfAccountListResponseModel_P6CyoERI> GetAccountListAsync(VakıfKatilimSrv.AccountListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://boa.net/BOA.Integration.CustomerTransaction/CustomerTransactionService/ICu" +
            "stomerTransactionService/GetCustomerTransactionSlipData", ReplyAction="http://boa.net/BOA.Integration.CustomerTransaction/CustomerTransactionService/ICu" +
            "stomerTransactionService/GetCustomerTransactionSlipDataResponse")]
        System.Threading.Tasks.Task<VakıfKatilimSrv.ResponseModelBaseOfCustomerTransactionSlipDataResponseModel_P6CyoERI> GetCustomerTransactionSlipDataAsync(VakıfKatilimSrv.CustomerTransactionRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ICustomerTransactionServiceChannel : VakıfKatilimSrv.ICustomerTransactionService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class CustomerTransactionServiceClient : System.ServiceModel.ClientBase<VakıfKatilimSrv.ICustomerTransactionService>, VakıfKatilimSrv.ICustomerTransactionService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CustomerTransactionServiceClient() : 
                base(CustomerTransactionServiceClient.GetDefaultBinding(), CustomerTransactionServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICustomerTransactionService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerTransactionServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CustomerTransactionServiceClient.GetBindingForEndpoint(endpointConfiguration), CustomerTransactionServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerTransactionServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CustomerTransactionServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerTransactionServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CustomerTransactionServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerTransactionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<VakıfKatilimSrv.ResponseModelBaseOfArrayOfCustomerTransactionResponseModel_P6CyoERI> GetCustomerTransactionsAsync(VakıfKatilimSrv.CustomerTransactionRequest request)
        {
            return base.Channel.GetCustomerTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<VakıfKatilimSrv.ResponseModelBaseOfArrayOfCustomerTransactionDetailResponseModel_P6CyoERI> GetCustomerTransactionDetailsAsync(VakıfKatilimSrv.CustomerTransactionRequest request)
        {
            return base.Channel.GetCustomerTransactionDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<VakıfKatilimSrv.ResponseModelBaseOfAccountBalanceResponseModel_P6CyoERI> GetAccountBalanceAsync(VakıfKatilimSrv.AccountBalanceRequest request)
        {
            return base.Channel.GetAccountBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<VakıfKatilimSrv.ResponseModelBaseOfArrayOfAccountListResponseModel_P6CyoERI> GetAccountListAsync(VakıfKatilimSrv.AccountListRequest request)
        {
            return base.Channel.GetAccountListAsync(request);
        }
        
        public System.Threading.Tasks.Task<VakıfKatilimSrv.ResponseModelBaseOfCustomerTransactionSlipDataResponseModel_P6CyoERI> GetCustomerTransactionSlipDataAsync(VakıfKatilimSrv.CustomerTransactionRequest request)
        {
            return base.Channel.GetCustomerTransactionSlipDataAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICustomerTransactionService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICustomerTransactionService))
            {
                return new System.ServiceModel.EndpointAddress("https://boa.vakifkatilim.com.tr/BOA.Integration.WCFService/BOA.Integration.Custom" +
                        "erTransaction/CustomerTransactionService.svc/Basic");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CustomerTransactionServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICustomerTransactionService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CustomerTransactionServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICustomerTransactionService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICustomerTransactionService,
        }
    }
}
