//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurkiyeFinansSrv
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movements", Namespace="http://schemas.datacontract.org/2004/07/TurkiyeFinans.Accounting.BankExtractForOu" +
        "tFirm.Entity.Constants")]
    public partial class Movements : object
    {
        
        private string hataKoduField;
        
        private string hataAciklamaField;
        
        private TurkiyeFinansSrv.AccountInformations HesapField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hataKodu
        {
            get
            {
                return this.hataKoduField;
            }
            set
            {
                this.hataKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string hataAciklama
        {
            get
            {
                return this.hataAciklamaField;
            }
            set
            {
                this.hataAciklamaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public TurkiyeFinansSrv.AccountInformations Hesap
        {
            get
            {
                return this.HesapField;
            }
            set
            {
                this.HesapField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountInformations", Namespace="http://schemas.datacontract.org/2004/07/TurkiyeFinans.Accounting.BankExtractForOu" +
        "tFirm.Entity.Constants")]
    public partial class AccountInformations : object
    {
        
        private string HesapNoField;
        
        private string IBANField;
        
        private string ParaKodField;
        
        private string MusteriNoField;
        
        private string SubeKoduField;
        
        private string SubeAdiField;
        
        private string HesapAcilisTarihiField;
        
        private string SonHareketTarihiField;
        
        private string BakiyeField;
        
        private TurkiyeFinansSrv.Hareket[] AktivitelerField;
        
        private string BlokeTutariField;
        
        private string AcilisBakiyesiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HesapNo
        {
            get
            {
                return this.HesapNoField;
            }
            set
            {
                this.HesapNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IBAN
        {
            get
            {
                return this.IBANField;
            }
            set
            {
                this.IBANField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParaKod
        {
            get
            {
                return this.ParaKodField;
            }
            set
            {
                this.ParaKodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string MusteriNo
        {
            get
            {
                return this.MusteriNoField;
            }
            set
            {
                this.MusteriNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string SubeKodu
        {
            get
            {
                return this.SubeKoduField;
            }
            set
            {
                this.SubeKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string SubeAdi
        {
            get
            {
                return this.SubeAdiField;
            }
            set
            {
                this.SubeAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string HesapAcilisTarihi
        {
            get
            {
                return this.HesapAcilisTarihiField;
            }
            set
            {
                this.HesapAcilisTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string SonHareketTarihi
        {
            get
            {
                return this.SonHareketTarihiField;
            }
            set
            {
                this.SonHareketTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string Bakiye
        {
            get
            {
                return this.BakiyeField;
            }
            set
            {
                this.BakiyeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public TurkiyeFinansSrv.Hareket[] Aktiviteler
        {
            get
            {
                return this.AktivitelerField;
            }
            set
            {
                this.AktivitelerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string BlokeTutari
        {
            get
            {
                return this.BlokeTutariField;
            }
            set
            {
                this.BlokeTutariField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string AcilisBakiyesi
        {
            get
            {
                return this.AcilisBakiyesiField;
            }
            set
            {
                this.AcilisBakiyesiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hareket", Namespace="http://schemas.datacontract.org/2004/07/TurkiyeFinans.Accounting.BankExtractForOu" +
        "tFirm.Entity.Constants")]
    public partial class Hareket : object
    {
        
        private string TarihField;
        
        private string IslemSaatiField;
        
        private string IslemSubeField;
        
        private string FisNoField;
        
        private string ValorField;
        
        private string TutarField;
        
        private string Aciklama1Field;
        
        private string Aciklama2Field;
        
        private string ProgramKodField;
        
        private string RefNoField;
        
        private string IslemSonuBakiyeField;
        
        private string IbanField;
        
        private string VknField;
        
        private string AdSoyadField;
        
        private string UniqueReferenceField;
        
        private string EftDescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tarih
        {
            get
            {
                return this.TarihField;
            }
            set
            {
                this.TarihField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string IslemSaati
        {
            get
            {
                return this.IslemSaatiField;
            }
            set
            {
                this.IslemSaatiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string IslemSube
        {
            get
            {
                return this.IslemSubeField;
            }
            set
            {
                this.IslemSubeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string FisNo
        {
            get
            {
                return this.FisNoField;
            }
            set
            {
                this.FisNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Tutar
        {
            get
            {
                return this.TutarField;
            }
            set
            {
                this.TutarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Aciklama1
        {
            get
            {
                return this.Aciklama1Field;
            }
            set
            {
                this.Aciklama1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Aciklama2
        {
            get
            {
                return this.Aciklama2Field;
            }
            set
            {
                this.Aciklama2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string ProgramKod
        {
            get
            {
                return this.ProgramKodField;
            }
            set
            {
                this.ProgramKodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string RefNo
        {
            get
            {
                return this.RefNoField;
            }
            set
            {
                this.RefNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string IslemSonuBakiye
        {
            get
            {
                return this.IslemSonuBakiyeField;
            }
            set
            {
                this.IslemSonuBakiyeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string Iban
        {
            get
            {
                return this.IbanField;
            }
            set
            {
                this.IbanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string Vkn
        {
            get
            {
                return this.VknField;
            }
            set
            {
                this.VknField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string AdSoyad
        {
            get
            {
                return this.AdSoyadField;
            }
            set
            {
                this.AdSoyadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public string UniqueReference
        {
            get
            {
                return this.UniqueReferenceField;
            }
            set
            {
                this.UniqueReferenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string EftDescription
        {
            get
            {
                return this.EftDescriptionField;
            }
            set
            {
                this.EftDescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IntegrationFault", Namespace="http://schemas.datacontract.org/2004/07/TurkiyeFinans.Core")]
    public partial class IntegrationFault : object
    {
        
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionMessage
        {
            get
            {
                return this.ExceptionMessageField;
            }
            set
            {
                this.ExceptionMessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TurkiyeFinansSrv.IBankExtractIntegrationService")]
    public interface IBankExtractIntegrationService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankExtractIntegrationService/QueryExtract", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TurkiyeFinansSrv.IntegrationFault), Action="http://tempuri.org/IBankExtractIntegrationService/QueryExtract", Name="IntegrationFault", Namespace="http://schemas.datacontract.org/2004/07/TurkiyeFinans.Core")]
        System.Threading.Tasks.Task<TurkiyeFinansSrv.BankExtractOutputPackage> QueryExtractAsync(TurkiyeFinansSrv.BankExtractInputPackage request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BankExtractInputPackage
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string KullaniciKod;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Sifre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string HesapNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string BaslangicTarihi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string BitisTarihi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string RefNo;
        
        public BankExtractInputPackage()
        {
        }
        
        public BankExtractInputPackage(string KullaniciKod, string Sifre, string HesapNo, string BaslangicTarihi, string BitisTarihi, string RefNo)
        {
            this.KullaniciKod = KullaniciKod;
            this.Sifre = Sifre;
            this.HesapNo = HesapNo;
            this.BaslangicTarihi = BaslangicTarihi;
            this.BitisTarihi = BitisTarihi;
            this.RefNo = RefNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BankExtractOutputPackage
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public TurkiyeFinansSrv.Movements Hareketler;
        
        public BankExtractOutputPackage()
        {
        }
        
        public BankExtractOutputPackage(TurkiyeFinansSrv.Movements Hareketler)
        {
            this.Hareketler = Hareketler;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IBankExtractIntegrationServiceChannel : TurkiyeFinansSrv.IBankExtractIntegrationService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class BankExtractIntegrationServiceClient : System.ServiceModel.ClientBase<TurkiyeFinansSrv.IBankExtractIntegrationService>, TurkiyeFinansSrv.IBankExtractIntegrationService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BankExtractIntegrationServiceClient() : 
                base(BankExtractIntegrationServiceClient.GetDefaultBinding(), BankExtractIntegrationServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.IntegrationBinding_IBankExtractIntegrationService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BankExtractIntegrationServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(BankExtractIntegrationServiceClient.GetBindingForEndpoint(endpointConfiguration), BankExtractIntegrationServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BankExtractIntegrationServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BankExtractIntegrationServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BankExtractIntegrationServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BankExtractIntegrationServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BankExtractIntegrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TurkiyeFinansSrv.BankExtractOutputPackage> TurkiyeFinansSrv.IBankExtractIntegrationService.QueryExtractAsync(TurkiyeFinansSrv.BankExtractInputPackage request)
        {
            return base.Channel.QueryExtractAsync(request);
        }
        
        public System.Threading.Tasks.Task<TurkiyeFinansSrv.BankExtractOutputPackage> QueryExtractAsync(string KullaniciKod, string Sifre, string HesapNo, string BaslangicTarihi, string BitisTarihi, string RefNo)
        {
            TurkiyeFinansSrv.BankExtractInputPackage inValue = new TurkiyeFinansSrv.BankExtractInputPackage();
            inValue.KullaniciKod = KullaniciKod;
            inValue.Sifre = Sifre;
            inValue.HesapNo = HesapNo;
            inValue.BaslangicTarihi = BaslangicTarihi;
            inValue.BitisTarihi = BitisTarihi;
            inValue.RefNo = RefNo;
            return ((TurkiyeFinansSrv.IBankExtractIntegrationService)(this)).QueryExtractAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IntegrationBinding_IBankExtractIntegrationService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IntegrationBinding_IBankExtractIntegrationService))
            {
                return new System.ServiceModel.EndpointAddress("https://appgateway.turkiyefinans.com.tr/TurkiyeFinans.Accounting/IBankExtractInte" +
                        "grationService.svc/basic");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BankExtractIntegrationServiceClient.GetBindingForEndpoint(EndpointConfiguration.IntegrationBinding_IBankExtractIntegrationService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BankExtractIntegrationServiceClient.GetEndpointAddress(EndpointConfiguration.IntegrationBinding_IBankExtractIntegrationService);
        }
        
        public enum EndpointConfiguration
        {
            
            IntegrationBinding_IBankExtractIntegrationService,
        }
    }
}
