//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VakıfSrv
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoEkstreSorgu", Namespace="http://schemas.datacontract.org/2004/07/Peak.Integration.ExternalInbound.Ekstre.D" +
        "ataTransferObjects")]
    public partial class DtoEkstreSorgu : object
    {
        
        private string MusteriNoField;
        
        private string KurumKullaniciField;
        
        private string SifreField;
        
        private string SorguBaslangicTarihiField;
        
        private string SorguBitisTarihiField;
        
        private string HesapNoField;
        
        private string HareketTipiField;
        
        private decimal EnDusukTutarField;
        
        private decimal EnYuksekTutarField;
        
        private string HesapAcilisTarihiField;
        
        private string HesapKapanisTarihiField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MusteriNo
        {
            get
            {
                return this.MusteriNoField;
            }
            set
            {
                this.MusteriNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string KurumKullanici
        {
            get
            {
                return this.KurumKullaniciField;
            }
            set
            {
                this.KurumKullaniciField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Sifre
        {
            get
            {
                return this.SifreField;
            }
            set
            {
                this.SifreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string SorguBaslangicTarihi
        {
            get
            {
                return this.SorguBaslangicTarihiField;
            }
            set
            {
                this.SorguBaslangicTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string SorguBitisTarihi
        {
            get
            {
                return this.SorguBitisTarihiField;
            }
            set
            {
                this.SorguBitisTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string HesapNo
        {
            get
            {
                return this.HesapNoField;
            }
            set
            {
                this.HesapNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string HareketTipi
        {
            get
            {
                return this.HareketTipiField;
            }
            set
            {
                this.HareketTipiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal EnDusukTutar
        {
            get
            {
                return this.EnDusukTutarField;
            }
            set
            {
                this.EnDusukTutarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public decimal EnYuksekTutar
        {
            get
            {
                return this.EnYuksekTutarField;
            }
            set
            {
                this.EnYuksekTutarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string HesapAcilisTarihi
        {
            get
            {
                return this.HesapAcilisTarihiField;
            }
            set
            {
                this.HesapAcilisTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string HesapKapanisTarihi
        {
            get
            {
                return this.HesapKapanisTarihiField;
            }
            set
            {
                this.HesapKapanisTarihiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoEkstreCevap", Namespace="http://schemas.datacontract.org/2004/07/Peak.Integration.ExternalInbound.Ekstre.D" +
        "ataTransferObjects")]
    public partial class DtoEkstreCevap : object
    {
        
        private string BankaKoduField;
        
        private string BankaAdiField;
        
        private string BankaVergiDairesiField;
        
        private string BankaVergiNumarasiField;
        
        private string IslemKoduField;
        
        private string IslemAciklamasiField;
        
        private VakıfSrv.DtoEkstreHesap[] HesaplarField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankaKodu
        {
            get
            {
                return this.BankaKoduField;
            }
            set
            {
                this.BankaKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string BankaAdi
        {
            get
            {
                return this.BankaAdiField;
            }
            set
            {
                this.BankaAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string BankaVergiDairesi
        {
            get
            {
                return this.BankaVergiDairesiField;
            }
            set
            {
                this.BankaVergiDairesiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string BankaVergiNumarasi
        {
            get
            {
                return this.BankaVergiNumarasiField;
            }
            set
            {
                this.BankaVergiNumarasiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string IslemKodu
        {
            get
            {
                return this.IslemKoduField;
            }
            set
            {
                this.IslemKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string IslemAciklamasi
        {
            get
            {
                return this.IslemAciklamasiField;
            }
            set
            {
                this.IslemAciklamasiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public VakıfSrv.DtoEkstreHesap[] Hesaplar
        {
            get
            {
                return this.HesaplarField;
            }
            set
            {
                this.HesaplarField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoEkstreHesap", Namespace="http://schemas.datacontract.org/2004/07/Peak.Integration.ExternalInbound.Ekstre.D" +
        "ataTransferObjects")]
    public partial class DtoEkstreHesap : object
    {
        
        private string HesapNoField;
        
        private string MusteriNoField;
        
        private string MusteriUnvaniField;
        
        private string SubeKoduField;
        
        private string SubeAdiField;
        
        private string DovizTipiField;
        
        private decimal AcilisBakiyeField;
        
        private decimal CariBakiyeField;
        
        private decimal KullanilabilirBakiyeField;
        
        private decimal KrediliBankomatLimitiField;
        
        private decimal KrediBakiyesiField;
        
        private string SonHareketTarihiField;
        
        private string VergiKimlikNumarasiField;
        
        private VakıfSrv.DtoEkstreHareket[] HareketlerField;
        
        private byte HesapTipiField;
        
        private string VadeBaslangicTarihiField;
        
        private string VadeBitisTarihiField;
        
        private decimal VadeSonuBeklenenBakiyeField;
        
        private decimal VadeFaizOraniField;
        
        private decimal VadeSonuOdenecekBrutFaizTutariField;
        
        private decimal VadeSonuOdenecekNetFaizTutariField;
        
        private string HesapNoIbanField;
        
        private bool HesapDurumuField;
        
        private decimal StopajField;
        
        private decimal VadeSonuVergiTutariField;
        
        private byte HesapTemditTuruField;
        
        private string HesapRumuzuField;
        
        private string VadeliHesapVirmanHesapNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HesapNo
        {
            get
            {
                return this.HesapNoField;
            }
            set
            {
                this.HesapNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MusteriNo
        {
            get
            {
                return this.MusteriNoField;
            }
            set
            {
                this.MusteriNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MusteriUnvani
        {
            get
            {
                return this.MusteriUnvaniField;
            }
            set
            {
                this.MusteriUnvaniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubeKodu
        {
            get
            {
                return this.SubeKoduField;
            }
            set
            {
                this.SubeKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string SubeAdi
        {
            get
            {
                return this.SubeAdiField;
            }
            set
            {
                this.SubeAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string DovizTipi
        {
            get
            {
                return this.DovizTipiField;
            }
            set
            {
                this.DovizTipiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public decimal AcilisBakiye
        {
            get
            {
                return this.AcilisBakiyeField;
            }
            set
            {
                this.AcilisBakiyeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal CariBakiye
        {
            get
            {
                return this.CariBakiyeField;
            }
            set
            {
                this.CariBakiyeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public decimal KullanilabilirBakiye
        {
            get
            {
                return this.KullanilabilirBakiyeField;
            }
            set
            {
                this.KullanilabilirBakiyeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public decimal KrediliBankomatLimiti
        {
            get
            {
                return this.KrediliBankomatLimitiField;
            }
            set
            {
                this.KrediliBankomatLimitiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public decimal KrediBakiyesi
        {
            get
            {
                return this.KrediBakiyesiField;
            }
            set
            {
                this.KrediBakiyesiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string SonHareketTarihi
        {
            get
            {
                return this.SonHareketTarihiField;
            }
            set
            {
                this.SonHareketTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string VergiKimlikNumarasi
        {
            get
            {
                return this.VergiKimlikNumarasiField;
            }
            set
            {
                this.VergiKimlikNumarasiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public VakıfSrv.DtoEkstreHareket[] Hareketler
        {
            get
            {
                return this.HareketlerField;
            }
            set
            {
                this.HareketlerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public byte HesapTipi
        {
            get
            {
                return this.HesapTipiField;
            }
            set
            {
                this.HesapTipiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string VadeBaslangicTarihi
        {
            get
            {
                return this.VadeBaslangicTarihiField;
            }
            set
            {
                this.VadeBaslangicTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string VadeBitisTarihi
        {
            get
            {
                return this.VadeBitisTarihiField;
            }
            set
            {
                this.VadeBitisTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public decimal VadeSonuBeklenenBakiye
        {
            get
            {
                return this.VadeSonuBeklenenBakiyeField;
            }
            set
            {
                this.VadeSonuBeklenenBakiyeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public decimal VadeFaizOrani
        {
            get
            {
                return this.VadeFaizOraniField;
            }
            set
            {
                this.VadeFaizOraniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public decimal VadeSonuOdenecekBrutFaizTutari
        {
            get
            {
                return this.VadeSonuOdenecekBrutFaizTutariField;
            }
            set
            {
                this.VadeSonuOdenecekBrutFaizTutariField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public decimal VadeSonuOdenecekNetFaizTutari
        {
            get
            {
                return this.VadeSonuOdenecekNetFaizTutariField;
            }
            set
            {
                this.VadeSonuOdenecekNetFaizTutariField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public string HesapNoIban
        {
            get
            {
                return this.HesapNoIbanField;
            }
            set
            {
                this.HesapNoIbanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public bool HesapDurumu
        {
            get
            {
                return this.HesapDurumuField;
            }
            set
            {
                this.HesapDurumuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public decimal Stopaj
        {
            get
            {
                return this.StopajField;
            }
            set
            {
                this.StopajField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=24)]
        public decimal VadeSonuVergiTutari
        {
            get
            {
                return this.VadeSonuVergiTutariField;
            }
            set
            {
                this.VadeSonuVergiTutariField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        public byte HesapTemditTuru
        {
            get
            {
                return this.HesapTemditTuruField;
            }
            set
            {
                this.HesapTemditTuruField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=26)]
        public string HesapRumuzu
        {
            get
            {
                return this.HesapRumuzuField;
            }
            set
            {
                this.HesapRumuzuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=27)]
        public string VadeliHesapVirmanHesapNo
        {
            get
            {
                return this.VadeliHesapVirmanHesapNoField;
            }
            set
            {
                this.VadeliHesapVirmanHesapNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoEkstreHareket", Namespace="http://schemas.datacontract.org/2004/07/Peak.Integration.ExternalInbound.Ekstre.D" +
        "ataTransferObjects")]
    public partial class DtoEkstreHareket : object
    {
        
        private string IslemTarihiField;
        
        private string IslemNoField;
        
        private string IslemAdiField;
        
        private decimal TutarField;
        
        private string BorcAlacakField;
        
        private string AciklamaField;
        
        private decimal IslemOncesiBakiyeField;
        
        private decimal IslemSonrasıBakiyeField;
        
        private string IslemYeriField;
        
        private string IslemKanalField;
        
        private string KartNoField;
        
        private string IslemKoduField;
        
        private System.Collections.Generic.Dictionary<string, string> DetaylarField;
        
        private string IslemTarihZamaniField;
        
        private long IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IslemTarihi
        {
            get
            {
                return this.IslemTarihiField;
            }
            set
            {
                this.IslemTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string IslemNo
        {
            get
            {
                return this.IslemNoField;
            }
            set
            {
                this.IslemNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string IslemAdi
        {
            get
            {
                return this.IslemAdiField;
            }
            set
            {
                this.IslemAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal Tutar
        {
            get
            {
                return this.TutarField;
            }
            set
            {
                this.TutarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string BorcAlacak
        {
            get
            {
                return this.BorcAlacakField;
            }
            set
            {
                this.BorcAlacakField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Aciklama
        {
            get
            {
                return this.AciklamaField;
            }
            set
            {
                this.AciklamaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public decimal IslemOncesiBakiye
        {
            get
            {
                return this.IslemOncesiBakiyeField;
            }
            set
            {
                this.IslemOncesiBakiyeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal IslemSonrasıBakiye
        {
            get
            {
                return this.IslemSonrasıBakiyeField;
            }
            set
            {
                this.IslemSonrasıBakiyeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string IslemYeri
        {
            get
            {
                return this.IslemYeriField;
            }
            set
            {
                this.IslemYeriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string IslemKanal
        {
            get
            {
                return this.IslemKanalField;
            }
            set
            {
                this.IslemKanalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string KartNo
        {
            get
            {
                return this.KartNoField;
            }
            set
            {
                this.KartNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string IslemKodu
        {
            get
            {
                return this.IslemKoduField;
            }
            set
            {
                this.IslemKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public System.Collections.Generic.Dictionary<string, string> Detaylar
        {
            get
            {
                return this.DetaylarField;
            }
            set
            {
                this.DetaylarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public string IslemTarihZamani
        {
            get
            {
                return this.IslemTarihZamaniField;
            }
            set
            {
                this.IslemTarihZamaniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoEkstreOzetCevap", Namespace="http://schemas.datacontract.org/2004/07/Peak.Integration.ExternalInbound.Ekstre.D" +
        "ataTransferObjects")]
    public partial class DtoEkstreOzetCevap : object
    {
        
        private string BankaKoduField;
        
        private string BankaAdiField;
        
        private string BankaVergiDairesiField;
        
        private string BankaVergiNumarasiField;
        
        private string IslemKoduField;
        
        private string IslemAciklamasiField;
        
        private VakıfSrv.DtoEkstreOzetHesap[] HesaplarField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankaKodu
        {
            get
            {
                return this.BankaKoduField;
            }
            set
            {
                this.BankaKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string BankaAdi
        {
            get
            {
                return this.BankaAdiField;
            }
            set
            {
                this.BankaAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string BankaVergiDairesi
        {
            get
            {
                return this.BankaVergiDairesiField;
            }
            set
            {
                this.BankaVergiDairesiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string BankaVergiNumarasi
        {
            get
            {
                return this.BankaVergiNumarasiField;
            }
            set
            {
                this.BankaVergiNumarasiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string IslemKodu
        {
            get
            {
                return this.IslemKoduField;
            }
            set
            {
                this.IslemKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string IslemAciklamasi
        {
            get
            {
                return this.IslemAciklamasiField;
            }
            set
            {
                this.IslemAciklamasiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public VakıfSrv.DtoEkstreOzetHesap[] Hesaplar
        {
            get
            {
                return this.HesaplarField;
            }
            set
            {
                this.HesaplarField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoEkstreOzetHesap", Namespace="http://schemas.datacontract.org/2004/07/Peak.Integration.ExternalInbound.Ekstre.D" +
        "ataTransferObjects")]
    public partial class DtoEkstreOzetHesap : object
    {
        
        private string HesapNoField;
        
        private string MusteriNoField;
        
        private string MusteriUnvaniField;
        
        private string SubeKoduField;
        
        private string SubeAdiField;
        
        private string DovizTipiField;
        
        private decimal AcilisBakiyeField;
        
        private decimal CariBakiyeField;
        
        private decimal KullanilabilirBakiyeField;
        
        private decimal KrediliBankomatLimitiField;
        
        private decimal KrediBakiyesiField;
        
        private string SonHareketTarihiField;
        
        private string VergiKimlikNumarasiField;
        
        private VakıfSrv.DtoEkstreOzetHareket[] HareketlerField;
        
        private byte HesapTipiField;
        
        private string VadeBaslangicTarihiField;
        
        private string VadeBitisTarihiField;
        
        private decimal VadeSonuBeklenenBakiyeField;
        
        private decimal VadeFaizOraniField;
        
        private decimal VadeSonuOdenecekBrutFaizTutariField;
        
        private decimal VadeSonuOdenecekNetFaizTutariField;
        
        private string HesapNoIbanField;
        
        private bool HesapDurumuField;
        
        private decimal StopajField;
        
        private decimal VadeSonuVergiTutariField;
        
        private byte HesapTemditTuruField;
        
        private string HesapRumuzuField;
        
        private string VadeliHesapVirmanHesapNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HesapNo
        {
            get
            {
                return this.HesapNoField;
            }
            set
            {
                this.HesapNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MusteriNo
        {
            get
            {
                return this.MusteriNoField;
            }
            set
            {
                this.MusteriNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MusteriUnvani
        {
            get
            {
                return this.MusteriUnvaniField;
            }
            set
            {
                this.MusteriUnvaniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubeKodu
        {
            get
            {
                return this.SubeKoduField;
            }
            set
            {
                this.SubeKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string SubeAdi
        {
            get
            {
                return this.SubeAdiField;
            }
            set
            {
                this.SubeAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string DovizTipi
        {
            get
            {
                return this.DovizTipiField;
            }
            set
            {
                this.DovizTipiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public decimal AcilisBakiye
        {
            get
            {
                return this.AcilisBakiyeField;
            }
            set
            {
                this.AcilisBakiyeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal CariBakiye
        {
            get
            {
                return this.CariBakiyeField;
            }
            set
            {
                this.CariBakiyeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public decimal KullanilabilirBakiye
        {
            get
            {
                return this.KullanilabilirBakiyeField;
            }
            set
            {
                this.KullanilabilirBakiyeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public decimal KrediliBankomatLimiti
        {
            get
            {
                return this.KrediliBankomatLimitiField;
            }
            set
            {
                this.KrediliBankomatLimitiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public decimal KrediBakiyesi
        {
            get
            {
                return this.KrediBakiyesiField;
            }
            set
            {
                this.KrediBakiyesiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string SonHareketTarihi
        {
            get
            {
                return this.SonHareketTarihiField;
            }
            set
            {
                this.SonHareketTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string VergiKimlikNumarasi
        {
            get
            {
                return this.VergiKimlikNumarasiField;
            }
            set
            {
                this.VergiKimlikNumarasiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public VakıfSrv.DtoEkstreOzetHareket[] Hareketler
        {
            get
            {
                return this.HareketlerField;
            }
            set
            {
                this.HareketlerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public byte HesapTipi
        {
            get
            {
                return this.HesapTipiField;
            }
            set
            {
                this.HesapTipiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string VadeBaslangicTarihi
        {
            get
            {
                return this.VadeBaslangicTarihiField;
            }
            set
            {
                this.VadeBaslangicTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string VadeBitisTarihi
        {
            get
            {
                return this.VadeBitisTarihiField;
            }
            set
            {
                this.VadeBitisTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public decimal VadeSonuBeklenenBakiye
        {
            get
            {
                return this.VadeSonuBeklenenBakiyeField;
            }
            set
            {
                this.VadeSonuBeklenenBakiyeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public decimal VadeFaizOrani
        {
            get
            {
                return this.VadeFaizOraniField;
            }
            set
            {
                this.VadeFaizOraniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public decimal VadeSonuOdenecekBrutFaizTutari
        {
            get
            {
                return this.VadeSonuOdenecekBrutFaizTutariField;
            }
            set
            {
                this.VadeSonuOdenecekBrutFaizTutariField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public decimal VadeSonuOdenecekNetFaizTutari
        {
            get
            {
                return this.VadeSonuOdenecekNetFaizTutariField;
            }
            set
            {
                this.VadeSonuOdenecekNetFaizTutariField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public string HesapNoIban
        {
            get
            {
                return this.HesapNoIbanField;
            }
            set
            {
                this.HesapNoIbanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public bool HesapDurumu
        {
            get
            {
                return this.HesapDurumuField;
            }
            set
            {
                this.HesapDurumuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public decimal Stopaj
        {
            get
            {
                return this.StopajField;
            }
            set
            {
                this.StopajField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=24)]
        public decimal VadeSonuVergiTutari
        {
            get
            {
                return this.VadeSonuVergiTutariField;
            }
            set
            {
                this.VadeSonuVergiTutariField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        public byte HesapTemditTuru
        {
            get
            {
                return this.HesapTemditTuruField;
            }
            set
            {
                this.HesapTemditTuruField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=26)]
        public string HesapRumuzu
        {
            get
            {
                return this.HesapRumuzuField;
            }
            set
            {
                this.HesapRumuzuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=27)]
        public string VadeliHesapVirmanHesapNo
        {
            get
            {
                return this.VadeliHesapVirmanHesapNoField;
            }
            set
            {
                this.VadeliHesapVirmanHesapNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoEkstreOzetHareket", Namespace="http://schemas.datacontract.org/2004/07/Peak.Integration.ExternalInbound.Ekstre.D" +
        "ataTransferObjects")]
    public partial class DtoEkstreOzetHareket : object
    {
        
        private string IslemTarihiField;
        
        private decimal GunBasiBakiyeField;
        
        private decimal GunSonuBakiyeField;
        
        private decimal ToplamAlacakField;
        
        private decimal ToplamBorcField;
        
        private decimal ToplamIslemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IslemTarihi
        {
            get
            {
                return this.IslemTarihiField;
            }
            set
            {
                this.IslemTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal GunBasiBakiye
        {
            get
            {
                return this.GunBasiBakiyeField;
            }
            set
            {
                this.GunBasiBakiyeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal GunSonuBakiye
        {
            get
            {
                return this.GunSonuBakiyeField;
            }
            set
            {
                this.GunSonuBakiyeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal ToplamAlacak
        {
            get
            {
                return this.ToplamAlacakField;
            }
            set
            {
                this.ToplamAlacakField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal ToplamBorc
        {
            get
            {
                return this.ToplamBorcField;
            }
            set
            {
                this.ToplamBorcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal ToplamIslem
        {
            get
            {
                return this.ToplamIslemField;
            }
            set
            {
                this.ToplamIslemField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoDekontSorgu", Namespace="http://schemas.datacontract.org/2004/07/Peak.Integration.ExternalInbound.Ekstre.D" +
        "ataTransferObjects")]
    public partial class DtoDekontSorgu : object
    {
        
        private string KurumKullaniciField;
        
        private string SifreField;
        
        private string MusteriNoField;
        
        private string IslemNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string KurumKullanici
        {
            get
            {
                return this.KurumKullaniciField;
            }
            set
            {
                this.KurumKullaniciField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Sifre
        {
            get
            {
                return this.SifreField;
            }
            set
            {
                this.SifreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string MusteriNo
        {
            get
            {
                return this.MusteriNoField;
            }
            set
            {
                this.MusteriNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string IslemNo
        {
            get
            {
                return this.IslemNoField;
            }
            set
            {
                this.IslemNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoDekontCevap", Namespace="http://schemas.datacontract.org/2004/07/Peak.Integration.ExternalInbound.Ekstre.D" +
        "ataTransferObjects")]
    public partial class DtoDekontCevap : object
    {
        
        private string IslemKoduField;
        
        private string IslemAciklamasiField;
        
        private byte[][] DekontListesiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IslemKodu
        {
            get
            {
                return this.IslemKoduField;
            }
            set
            {
                this.IslemKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string IslemAciklamasi
        {
            get
            {
                return this.IslemAciklamasiField;
            }
            set
            {
                this.IslemAciklamasiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public byte[][] DekontListesi
        {
            get
            {
                return this.DekontListesiField;
            }
            set
            {
                this.DekontListesiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoEkstreYatirimSonuc", Namespace="http://schemas.datacontract.org/2004/07/Peak.Integration.ExternalInbound.Ekstre.D" +
        "ataTransferObjects")]
    public partial class DtoEkstreYatirimSonuc : object
    {
        
        private string BankaAdiField;
        
        private string BankaKoduField;
        
        private string BankaVergiDairesiField;
        
        private string HataKoduField;
        
        private string HataAciklamasiField;
        
        private VakıfSrv.DtoEkstreYatirimHesap[] HesaplarField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BankaAdi
        {
            get
            {
                return this.BankaAdiField;
            }
            set
            {
                this.BankaAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BankaKodu
        {
            get
            {
                return this.BankaKoduField;
            }
            set
            {
                this.BankaKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BankaVergiDairesi
        {
            get
            {
                return this.BankaVergiDairesiField;
            }
            set
            {
                this.BankaVergiDairesiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string HataKodu
        {
            get
            {
                return this.HataKoduField;
            }
            set
            {
                this.HataKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string HataAciklamasi
        {
            get
            {
                return this.HataAciklamasiField;
            }
            set
            {
                this.HataAciklamasiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public VakıfSrv.DtoEkstreYatirimHesap[] Hesaplar
        {
            get
            {
                return this.HesaplarField;
            }
            set
            {
                this.HesaplarField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoEkstreYatirimHesap", Namespace="http://schemas.datacontract.org/2004/07/Peak.Integration.ExternalInbound.Ekstre.D" +
        "ataTransferObjects")]
    public partial class DtoEkstreYatirimHesap : object
    {
        
        private decimal BakiyeField;
        
        private decimal BlokeMiktariField;
        
        private string DovizCinsiField;
        
        private byte DurumKoduField;
        
        private string HesapSubeKoduField;
        
        private long IdField;
        
        private decimal KullanilabilirBakiyeField;
        
        private VakıfSrv.DtoEkstreYatirimHareket[] MenkulHareketField;
        
        private string MusteriAdiField;
        
        private string MusteriNoField;
        
        private string MusteriSoyadiField;
        
        private VakıfSrv.DtoEkstreYatirimMusteriPortfoy[] PortfoyField;
        
        private System.DateTime SonHareketTarihiField;
        
        private VakıfSrv.DtoEkstreYatirimHareket[] TLHareketField;
        
        private int YatirimHesapNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public decimal Bakiye
        {
            get
            {
                return this.BakiyeField;
            }
            set
            {
                this.BakiyeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public decimal BlokeMiktari
        {
            get
            {
                return this.BlokeMiktariField;
            }
            set
            {
                this.BlokeMiktariField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DovizCinsi
        {
            get
            {
                return this.DovizCinsiField;
            }
            set
            {
                this.DovizCinsiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte DurumKodu
        {
            get
            {
                return this.DurumKoduField;
            }
            set
            {
                this.DurumKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string HesapSubeKodu
        {
            get
            {
                return this.HesapSubeKoduField;
            }
            set
            {
                this.HesapSubeKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public decimal KullanilabilirBakiye
        {
            get
            {
                return this.KullanilabilirBakiyeField;
            }
            set
            {
                this.KullanilabilirBakiyeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public VakıfSrv.DtoEkstreYatirimHareket[] MenkulHareket
        {
            get
            {
                return this.MenkulHareketField;
            }
            set
            {
                this.MenkulHareketField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MusteriAdi
        {
            get
            {
                return this.MusteriAdiField;
            }
            set
            {
                this.MusteriAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MusteriNo
        {
            get
            {
                return this.MusteriNoField;
            }
            set
            {
                this.MusteriNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MusteriSoyadi
        {
            get
            {
                return this.MusteriSoyadiField;
            }
            set
            {
                this.MusteriSoyadiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public VakıfSrv.DtoEkstreYatirimMusteriPortfoy[] Portfoy
        {
            get
            {
                return this.PortfoyField;
            }
            set
            {
                this.PortfoyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.DateTime SonHareketTarihi
        {
            get
            {
                return this.SonHareketTarihiField;
            }
            set
            {
                this.SonHareketTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public VakıfSrv.DtoEkstreYatirimHareket[] TLHareket
        {
            get
            {
                return this.TLHareketField;
            }
            set
            {
                this.TLHareketField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int YatirimHesapNo
        {
            get
            {
                return this.YatirimHesapNoField;
            }
            set
            {
                this.YatirimHesapNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoEkstreYatirimHareket", Namespace="http://schemas.datacontract.org/2004/07/Peak.Integration.ExternalInbound.Ekstre.D" +
        "ataTransferObjects")]
    public partial class DtoEkstreYatirimHareket : object
    {
        
        private string AciklamaField;
        
        private decimal AdetField;
        
        private decimal BakiyeField;
        
        private System.DateTime BaslangicTarihiField;
        
        private System.DateTime BitisTarihiField;
        
        private string EPostaAdresiField;
        
        private int HareketTipiField;
        
        private string ISINField;
        
        private long IdField;
        
        private System.DateTime IslemTarihiField;
        
        private string IslemTuruStrField;
        
        private decimal IslemTutariField;
        
        private string UrunKisaAdiField;
        
        private decimal YeniAdetField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Aciklama
        {
            get
            {
                return this.AciklamaField;
            }
            set
            {
                this.AciklamaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public decimal Adet
        {
            get
            {
                return this.AdetField;
            }
            set
            {
                this.AdetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public decimal Bakiye
        {
            get
            {
                return this.BakiyeField;
            }
            set
            {
                this.BakiyeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.DateTime BaslangicTarihi
        {
            get
            {
                return this.BaslangicTarihiField;
            }
            set
            {
                this.BaslangicTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.DateTime BitisTarihi
        {
            get
            {
                return this.BitisTarihiField;
            }
            set
            {
                this.BitisTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EPostaAdresi
        {
            get
            {
                return this.EPostaAdresiField;
            }
            set
            {
                this.EPostaAdresiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int HareketTipi
        {
            get
            {
                return this.HareketTipiField;
            }
            set
            {
                this.HareketTipiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ISIN
        {
            get
            {
                return this.ISINField;
            }
            set
            {
                this.ISINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.DateTime IslemTarihi
        {
            get
            {
                return this.IslemTarihiField;
            }
            set
            {
                this.IslemTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IslemTuruStr
        {
            get
            {
                return this.IslemTuruStrField;
            }
            set
            {
                this.IslemTuruStrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public decimal IslemTutari
        {
            get
            {
                return this.IslemTutariField;
            }
            set
            {
                this.IslemTutariField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UrunKisaAdi
        {
            get
            {
                return this.UrunKisaAdiField;
            }
            set
            {
                this.UrunKisaAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public decimal YeniAdet
        {
            get
            {
                return this.YeniAdetField;
            }
            set
            {
                this.YeniAdetField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoEkstreYatirimMusteriPortfoy", Namespace="http://schemas.datacontract.org/2004/07/Peak.Integration.ExternalInbound.Ekstre.D" +
        "ataTransferObjects")]
    public partial class DtoEkstreYatirimMusteriPortfoy : object
    {
        
        private decimal AdetField;
        
        private decimal BlokeAdediField;
        
        private string ISINField;
        
        private long IdField;
        
        private decimal TLKarsiligiField;
        
        private string UrunAdiField;
        
        private string UrunAileAdiField;
        
        private string UrunGrupAdiField;
        
        private string UrunKisaAdiField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public decimal Adet
        {
            get
            {
                return this.AdetField;
            }
            set
            {
                this.AdetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public decimal BlokeAdedi
        {
            get
            {
                return this.BlokeAdediField;
            }
            set
            {
                this.BlokeAdediField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ISIN
        {
            get
            {
                return this.ISINField;
            }
            set
            {
                this.ISINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public decimal TLKarsiligi
        {
            get
            {
                return this.TLKarsiligiField;
            }
            set
            {
                this.TLKarsiligiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UrunAdi
        {
            get
            {
                return this.UrunAdiField;
            }
            set
            {
                this.UrunAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UrunAileAdi
        {
            get
            {
                return this.UrunAileAdiField;
            }
            set
            {
                this.UrunAileAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UrunGrupAdi
        {
            get
            {
                return this.UrunGrupAdiField;
            }
            set
            {
                this.UrunGrupAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UrunKisaAdi
        {
            get
            {
                return this.UrunKisaAdiField;
            }
            set
            {
                this.UrunKisaAdiField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoOnlineEkstreUyeIsYeriSonuc", Namespace="http://schemas.datacontract.org/2004/07/Peak.Integration.ExternalInbound.Ekstre.D" +
        "ataTransferObjects")]
    public partial class DtoOnlineEkstreUyeIsYeriSonuc : object
    {
        
        private string BankaAdiField;
        
        private string BankaKoduField;
        
        private string BankaVergiDairesiField;
        
        private string HataKoduField;
        
        private string HataAciklamasiField;
        
        private string BankaVergiNumarasiField;
        
        private VakıfSrv.DtoOnlineEkstreUyeIsYeriCevap[] UyeIsYeriCevapField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BankaAdi
        {
            get
            {
                return this.BankaAdiField;
            }
            set
            {
                this.BankaAdiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BankaKodu
        {
            get
            {
                return this.BankaKoduField;
            }
            set
            {
                this.BankaKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BankaVergiDairesi
        {
            get
            {
                return this.BankaVergiDairesiField;
            }
            set
            {
                this.BankaVergiDairesiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string HataKodu
        {
            get
            {
                return this.HataKoduField;
            }
            set
            {
                this.HataKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string HataAciklamasi
        {
            get
            {
                return this.HataAciklamasiField;
            }
            set
            {
                this.HataAciklamasiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string BankaVergiNumarasi
        {
            get
            {
                return this.BankaVergiNumarasiField;
            }
            set
            {
                this.BankaVergiNumarasiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public VakıfSrv.DtoOnlineEkstreUyeIsYeriCevap[] UyeIsYeriCevap
        {
            get
            {
                return this.UyeIsYeriCevapField;
            }
            set
            {
                this.UyeIsYeriCevapField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DtoOnlineEkstreUyeIsYeriCevap", Namespace="http://schemas.datacontract.org/2004/07/Peak.Integration.ExternalInbound.Ekstre.D" +
        "ataTransferObjects")]
    public partial class DtoOnlineEkstreUyeIsYeriCevap : object
    {
        
        private string ZincirNoField;
        
        private decimal VakifParaField;
        
        private string VadesizHesapNoField;
        
        private string UyeRefNoField;
        
        private string UyeNoField;
        
        private string UyeAdField;
        
        private int UTSField;
        
        private string TransactionIdField;
        
        private string TaksitSiraField;
        
        private int TaksitSayisiField;
        
        private string ServisKoduField;
        
        private string PosNoField;
        
        private string ParaCinsiField;
        
        private decimal OrijinalNetTutarField;
        
        private decimal OrijinalKomisyonField;
        
        private decimal OrijinalIslemTutariField;
        
        private string OnayKoduField;
        
        private decimal NetTutarField;
        
        private decimal KurBilgisiField;
        
        private decimal KomisyonOraniField;
        
        private decimal KomisyonField;
        
        private string KartTipiField;
        
        private string KartNoField;
        
        private System.DateTime IslenmeTarihiField;
        
        private string IslemTipiField;
        
        private System.DateTime IslemTarihiField;
        
        private string IslemSaatiField;
        
        private System.DateTime HesabaGecisTarihiField;
        
        private decimal CaprazKurBilgisiField;
        
        private decimal BrutTutarField;
        
        private string BlokeTipiField;
        
        private int BlokeSuresiField;
        
        private string BayiKoduField;
        
        private string BatchNoField;
        
        private string AnaIsYeriNoField;
        
        private string AboneNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ZincirNo
        {
            get
            {
                return this.ZincirNoField;
            }
            set
            {
                this.ZincirNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public decimal VakifPara
        {
            get
            {
                return this.VakifParaField;
            }
            set
            {
                this.VakifParaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string VadesizHesapNo
        {
            get
            {
                return this.VadesizHesapNoField;
            }
            set
            {
                this.VadesizHesapNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UyeRefNo
        {
            get
            {
                return this.UyeRefNoField;
            }
            set
            {
                this.UyeRefNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string UyeNo
        {
            get
            {
                return this.UyeNoField;
            }
            set
            {
                this.UyeNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string UyeAd
        {
            get
            {
                return this.UyeAdField;
            }
            set
            {
                this.UyeAdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public int UTS
        {
            get
            {
                return this.UTSField;
            }
            set
            {
                this.UTSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string TransactionId
        {
            get
            {
                return this.TransactionIdField;
            }
            set
            {
                this.TransactionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string TaksitSira
        {
            get
            {
                return this.TaksitSiraField;
            }
            set
            {
                this.TaksitSiraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public int TaksitSayisi
        {
            get
            {
                return this.TaksitSayisiField;
            }
            set
            {
                this.TaksitSayisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ServisKodu
        {
            get
            {
                return this.ServisKoduField;
            }
            set
            {
                this.ServisKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string PosNo
        {
            get
            {
                return this.PosNoField;
            }
            set
            {
                this.PosNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ParaCinsi
        {
            get
            {
                return this.ParaCinsiField;
            }
            set
            {
                this.ParaCinsiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public decimal OrijinalNetTutar
        {
            get
            {
                return this.OrijinalNetTutarField;
            }
            set
            {
                this.OrijinalNetTutarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public decimal OrijinalKomisyon
        {
            get
            {
                return this.OrijinalKomisyonField;
            }
            set
            {
                this.OrijinalKomisyonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public decimal OrijinalIslemTutari
        {
            get
            {
                return this.OrijinalIslemTutariField;
            }
            set
            {
                this.OrijinalIslemTutariField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string OnayKodu
        {
            get
            {
                return this.OnayKoduField;
            }
            set
            {
                this.OnayKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public decimal NetTutar
        {
            get
            {
                return this.NetTutarField;
            }
            set
            {
                this.NetTutarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public decimal KurBilgisi
        {
            get
            {
                return this.KurBilgisiField;
            }
            set
            {
                this.KurBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public decimal KomisyonOrani
        {
            get
            {
                return this.KomisyonOraniField;
            }
            set
            {
                this.KomisyonOraniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public decimal Komisyon
        {
            get
            {
                return this.KomisyonField;
            }
            set
            {
                this.KomisyonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string KartTipi
        {
            get
            {
                return this.KartTipiField;
            }
            set
            {
                this.KartTipiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string KartNo
        {
            get
            {
                return this.KartNoField;
            }
            set
            {
                this.KartNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public System.DateTime IslenmeTarihi
        {
            get
            {
                return this.IslenmeTarihiField;
            }
            set
            {
                this.IslenmeTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string IslemTipi
        {
            get
            {
                return this.IslemTipiField;
            }
            set
            {
                this.IslemTipiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public System.DateTime IslemTarihi
        {
            get
            {
                return this.IslemTarihiField;
            }
            set
            {
                this.IslemTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string IslemSaati
        {
            get
            {
                return this.IslemSaatiField;
            }
            set
            {
                this.IslemSaatiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public System.DateTime HesabaGecisTarihi
        {
            get
            {
                return this.HesabaGecisTarihiField;
            }
            set
            {
                this.HesabaGecisTarihiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public decimal CaprazKurBilgisi
        {
            get
            {
                return this.CaprazKurBilgisiField;
            }
            set
            {
                this.CaprazKurBilgisiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=29)]
        public decimal BrutTutar
        {
            get
            {
                return this.BrutTutarField;
            }
            set
            {
                this.BrutTutarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=30)]
        public string BlokeTipi
        {
            get
            {
                return this.BlokeTipiField;
            }
            set
            {
                this.BlokeTipiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public int BlokeSuresi
        {
            get
            {
                return this.BlokeSuresiField;
            }
            set
            {
                this.BlokeSuresiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=32)]
        public string BayiKodu
        {
            get
            {
                return this.BayiKoduField;
            }
            set
            {
                this.BayiKoduField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=33)]
        public string BatchNo
        {
            get
            {
                return this.BatchNoField;
            }
            set
            {
                this.BatchNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=34)]
        public string AnaIsYeriNo
        {
            get
            {
                return this.AnaIsYeriNoField;
            }
            set
            {
                this.AnaIsYeriNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=35)]
        public string AboneNo
        {
            get
            {
                return this.AboneNoField;
            }
            set
            {
                this.AboneNoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Peak.Integration.ExternalInbound.Ekstre", ConfigurationName="VakıfSrv.ISOnlineEkstreServis")]
    public interface ISOnlineEkstreServis
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="Peak.Integration.ExternalInbound.Ekstre/ISOnlineEkstreServis/GetirHareket", ReplyAction="Peak.Integration.ExternalInbound.Ekstre/ISOnlineEkstreServis/GetirHareketResponse" +
            "")]
        System.Threading.Tasks.Task<VakıfSrv.DtoEkstreCevap> GetirHareketAsync(VakıfSrv.DtoEkstreSorgu sorgu);
        
        [System.ServiceModel.OperationContractAttribute(Action="Peak.Integration.ExternalInbound.Ekstre/ISOnlineEkstreServis/GetirHareketOzet", ReplyAction="Peak.Integration.ExternalInbound.Ekstre/ISOnlineEkstreServis/GetirHareketOzetResp" +
            "onse")]
        System.Threading.Tasks.Task<VakıfSrv.DtoEkstreOzetCevap> GetirHareketOzetAsync(VakıfSrv.DtoEkstreSorgu sorgu);
        
        [System.ServiceModel.OperationContractAttribute(Action="Peak.Integration.ExternalInbound.Ekstre/ISOnlineEkstreServis/GetirDekont", ReplyAction="Peak.Integration.ExternalInbound.Ekstre/ISOnlineEkstreServis/GetirDekontResponse")]
        System.Threading.Tasks.Task<VakıfSrv.DtoDekontCevap> GetirDekontAsync(VakıfSrv.DtoDekontSorgu sorgu);
        
        [System.ServiceModel.OperationContractAttribute(Action="Peak.Integration.ExternalInbound.Ekstre/ISOnlineEkstreServis/GetirYatirimHareket", ReplyAction="Peak.Integration.ExternalInbound.Ekstre/ISOnlineEkstreServis/GetirYatirimHareketR" +
            "esponse")]
        System.Threading.Tasks.Task<VakıfSrv.DtoEkstreYatirimSonuc> GetirYatirimHareketAsync(VakıfSrv.DtoEkstreSorgu sorgu);
        
        [System.ServiceModel.OperationContractAttribute(Action="Peak.Integration.ExternalInbound.Ekstre/ISOnlineEkstreServis/GetirUyeIsyeriHareke" +
            "t", ReplyAction="Peak.Integration.ExternalInbound.Ekstre/ISOnlineEkstreServis/GetirUyeIsyeriHareke" +
            "tResponse")]
        System.Threading.Tasks.Task<VakıfSrv.DtoOnlineEkstreUyeIsYeriSonuc> GetirUyeIsyeriHareketAsync(VakıfSrv.DtoEkstreSorgu sorgu);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ISOnlineEkstreServisChannel : VakıfSrv.ISOnlineEkstreServis, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class SOnlineEkstreServisClient : System.ServiceModel.ClientBase<VakıfSrv.ISOnlineEkstreServis>, VakıfSrv.ISOnlineEkstreServis
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SOnlineEkstreServisClient() : 
                base(SOnlineEkstreServisClient.GetDefaultBinding(), SOnlineEkstreServisClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.MetadataExchangeHttpsBinding_ISOnlineEkstreServis.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SOnlineEkstreServisClient(EndpointConfiguration endpointConfiguration) : 
                base(SOnlineEkstreServisClient.GetBindingForEndpoint(endpointConfiguration), SOnlineEkstreServisClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SOnlineEkstreServisClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SOnlineEkstreServisClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SOnlineEkstreServisClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SOnlineEkstreServisClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SOnlineEkstreServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<VakıfSrv.DtoEkstreCevap> GetirHareketAsync(VakıfSrv.DtoEkstreSorgu sorgu)
        {
            return base.Channel.GetirHareketAsync(sorgu);
        }
        
        public System.Threading.Tasks.Task<VakıfSrv.DtoEkstreOzetCevap> GetirHareketOzetAsync(VakıfSrv.DtoEkstreSorgu sorgu)
        {
            return base.Channel.GetirHareketOzetAsync(sorgu);
        }
        
        public System.Threading.Tasks.Task<VakıfSrv.DtoDekontCevap> GetirDekontAsync(VakıfSrv.DtoDekontSorgu sorgu)
        {
            return base.Channel.GetirDekontAsync(sorgu);
        }
        
        public System.Threading.Tasks.Task<VakıfSrv.DtoEkstreYatirimSonuc> GetirYatirimHareketAsync(VakıfSrv.DtoEkstreSorgu sorgu)
        {
            return base.Channel.GetirYatirimHareketAsync(sorgu);
        }
        
        public System.Threading.Tasks.Task<VakıfSrv.DtoOnlineEkstreUyeIsYeriSonuc> GetirUyeIsyeriHareketAsync(VakıfSrv.DtoEkstreSorgu sorgu)
        {
            return base.Channel.GetirUyeIsyeriHareketAsync(sorgu);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MetadataExchangeHttpsBinding_ISOnlineEkstreServis))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.Transport;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.MetadataExchangeHttpsBinding_ISOnlineEkstreServis))
            {
                return new System.ServiceModel.EndpointAddress("https://vbservice.vakifbank.com.tr/HesapHareketleri.OnlineEkstre/SOnlineEkstreSer" +
                        "vis.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SOnlineEkstreServisClient.GetBindingForEndpoint(EndpointConfiguration.MetadataExchangeHttpsBinding_ISOnlineEkstreServis);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SOnlineEkstreServisClient.GetEndpointAddress(EndpointConfiguration.MetadataExchangeHttpsBinding_ISOnlineEkstreServis);
        }
        
        public enum EndpointConfiguration
        {
            
            MetadataExchangeHttpsBinding_ISOnlineEkstreServis,
        }
    }
}
