//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakSrv
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModelBase", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Base")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmlakSrv.ResponseModelBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmlakSrv.ResponseModelBaseOfArrayOfAccountContractNx15LZU3))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmlakSrv.RequestModelBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmlakSrv.AccountStatetmentRequest))]
    public partial class ModelBase : object
    {
        
        private string EncryptedValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string EncryptedValue
        {
            get
            {
                return this.EncryptedValueField;
            }
            set
            {
                this.EncryptedValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseModelBase", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Base")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmlakSrv.ResponseModelBaseOfArrayOfAccountContractNx15LZU3))]
    public partial class ResponseModelBase : EmlakSrv.ModelBase
    {
        
        private EmlakSrv.Result[] ResultsField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public EmlakSrv.Result[] Results
        {
            get
            {
                return this.ResultsField;
            }
            set
            {
                this.ResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseModelBaseOfArrayOfAccountContractNx15LZU3", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Base")]
    public partial class ResponseModelBaseOfArrayOfAccountContractNx15LZU3 : EmlakSrv.ResponseModelBase
    {
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private EmlakSrv.AccountContract[] ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public EmlakSrv.AccountContract[] Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestModelBase", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Base")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(EmlakSrv.AccountStatetmentRequest))]
    public partial class RequestModelBase : EmlakSrv.ModelBase
    {
        
        private string AppNameField;
        
        private string DeviceIdField;
        
        private string DeviceModelField;
        
        private string DeviceOSNameField;
        
        private string DeviceOSVersionField;
        
        private string ExtUNameField;
        
        private string ExtUPasswordField;
        
        private string ExtUSessionKeyField;
        
        private System.Nullable<bool> IsDeviceRootedField;
        
        private System.Nullable<int> LanguageIdField;
        
        private string MainResourceCodeField;
        
        private System.Nullable<int> MainResourceIdField;
        
        private string MethodNameField;
        
        private string VersionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AppName
        {
            get
            {
                return this.AppNameField;
            }
            set
            {
                this.AppNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DeviceId
        {
            get
            {
                return this.DeviceIdField;
            }
            set
            {
                this.DeviceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DeviceModel
        {
            get
            {
                return this.DeviceModelField;
            }
            set
            {
                this.DeviceModelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DeviceOSName
        {
            get
            {
                return this.DeviceOSNameField;
            }
            set
            {
                this.DeviceOSNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DeviceOSVersion
        {
            get
            {
                return this.DeviceOSVersionField;
            }
            set
            {
                this.DeviceOSVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtUName
        {
            get
            {
                return this.ExtUNameField;
            }
            set
            {
                this.ExtUNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtUPassword
        {
            get
            {
                return this.ExtUPasswordField;
            }
            set
            {
                this.ExtUPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ExtUSessionKey
        {
            get
            {
                return this.ExtUSessionKeyField;
            }
            set
            {
                this.ExtUSessionKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<bool> IsDeviceRooted
        {
            get
            {
                return this.IsDeviceRootedField;
            }
            set
            {
                this.IsDeviceRootedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> LanguageId
        {
            get
            {
                return this.LanguageIdField;
            }
            set
            {
                this.LanguageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MainResourceCode
        {
            get
            {
                return this.MainResourceCodeField;
            }
            set
            {
                this.MainResourceCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<int> MainResourceId
        {
            get
            {
                return this.MainResourceIdField;
            }
            set
            {
                this.MainResourceIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MethodName
        {
            get
            {
                return this.MethodNameField;
            }
            set
            {
                this.MethodNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountStatetmentRequest", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CoreBanking.Teller")]
    public partial class AccountStatetmentRequest : EmlakSrv.RequestModelBase
    {
        
        private System.Nullable<int> AccountNumberField;
        
        private System.Nullable<short> AccountSuffixField;
        
        private System.Nullable<System.DateTime> BeginDateField;
        
        private System.Nullable<System.DateTime> EndDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> AccountSuffix
        {
            get
            {
                return this.AccountSuffixField;
            }
            set
            {
                this.AccountSuffixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BeginDate
        {
            get
            {
                return this.BeginDateField;
            }
            set
            {
                this.BeginDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDate
        {
            get
            {
                return this.EndDateField;
            }
            set
            {
                this.EndDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Base")]
    public partial class Result : object
    {
        
        private string ErrorCodeField;
        
        private string ErrorMessageField;
        
        private string ExceptionField;
        
        private bool IsFriendlyField;
        
        private string[] ParamsField;
        
        private EmlakSrv.Severity SeverityField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Exception
        {
            get
            {
                return this.ExceptionField;
            }
            set
            {
                this.ExceptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool IsFriendly
        {
            get
            {
                return this.IsFriendlyField;
            }
            set
            {
                this.IsFriendlyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string[] Params
        {
            get
            {
                return this.ParamsField;
            }
            set
            {
                this.ParamsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public EmlakSrv.Severity Severity
        {
            get
            {
                return this.SeverityField;
            }
            set
            {
                this.SeverityField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Severity", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Base")]
    public enum Severity : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Information = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BusinessError = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountContract", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CoreBanking.Teller")]
    public partial class AccountContract : object
    {
        
        private string AccountAliasField;
        
        private int AccountNumberField;
        
        private short AccountSuffixField;
        
        private decimal AvailableBalanceField;
        
        private decimal BalanceField;
        
        private short BranchIdField;
        
        private string BranchNameField;
        
        private EmlakSrv.TransactionDetailContract[] DetailsField;
        
        private short FECField;
        
        private string FECLongNameField;
        
        private string FECNameField;
        
        private string IBANField;
        
        private System.Nullable<System.DateTime> InternalPeriodEndField;
        
        private System.Nullable<System.DateTime> LastRenewedDateField;
        
        private System.Nullable<System.DateTime> LastTranDateField;
        
        private System.Nullable<System.DateTime> MaturityEndField;
        
        private System.DateTime OpenDateField;
        
        private string ProductCodeField;
        
        private string TCKNorTaxNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AccountAlias
        {
            get
            {
                return this.AccountAliasField;
            }
            set
            {
                this.AccountAliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short AccountSuffix
        {
            get
            {
                return this.AccountSuffixField;
            }
            set
            {
                this.AccountSuffixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal AvailableBalance
        {
            get
            {
                return this.AvailableBalanceField;
            }
            set
            {
                this.AvailableBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Balance
        {
            get
            {
                return this.BalanceField;
            }
            set
            {
                this.BalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short BranchId
        {
            get
            {
                return this.BranchIdField;
            }
            set
            {
                this.BranchIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string BranchName
        {
            get
            {
                return this.BranchNameField;
            }
            set
            {
                this.BranchNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public EmlakSrv.TransactionDetailContract[] Details
        {
            get
            {
                return this.DetailsField;
            }
            set
            {
                this.DetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short FEC
        {
            get
            {
                return this.FECField;
            }
            set
            {
                this.FECField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FECLongName
        {
            get
            {
                return this.FECLongNameField;
            }
            set
            {
                this.FECLongNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FECName
        {
            get
            {
                return this.FECNameField;
            }
            set
            {
                this.FECNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IBAN
        {
            get
            {
                return this.IBANField;
            }
            set
            {
                this.IBANField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> InternalPeriodEnd
        {
            get
            {
                return this.InternalPeriodEndField;
            }
            set
            {
                this.InternalPeriodEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> LastRenewedDate
        {
            get
            {
                return this.LastRenewedDateField;
            }
            set
            {
                this.LastRenewedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> LastTranDate
        {
            get
            {
                return this.LastTranDateField;
            }
            set
            {
                this.LastTranDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> MaturityEnd
        {
            get
            {
                return this.MaturityEndField;
            }
            set
            {
                this.MaturityEndField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime OpenDate
        {
            get
            {
                return this.OpenDateField;
            }
            set
            {
                this.OpenDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ProductCode
        {
            get
            {
                return this.ProductCodeField;
            }
            set
            {
                this.ProductCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TCKNorTaxNumber
        {
            get
            {
                return this.TCKNorTaxNumberField;
            }
            set
            {
                this.TCKNorTaxNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionDetailContract", Namespace="http://schemas.datacontract.org/2004/07/BOA.Integration.Model.CoreBanking.Teller")]
    public partial class TransactionDetailContract : object
    {
        
        private decimal AmountField;
        
        private int BranchIdField;
        
        private string BranchNameField;
        
        private System.Nullable<decimal> BusinessKeyField;
        
        private System.Nullable<short> ChannelIdField;
        
        private decimal CreditField;
        
        private decimal CurrentBalanceField;
        
        private decimal DebitField;
        
        private string DescriptionField;
        
        private byte FECField;
        
        private string FECNameField;
        
        private string ReceiverIBANField;
        
        private string ResourceCodeField;
        
        private string SenderIBANField;
        
        private string SenderIdentityNumberField;
        
        private System.DateTime SystemDateField;
        
        private System.DateTime TranDateField;
        
        private string TranRefField;
        
        private string TranTypeField;
        
        private System.Nullable<System.DateTime> ValueDateField;
        
        private string VirtualIBANField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BranchId
        {
            get
            {
                return this.BranchIdField;
            }
            set
            {
                this.BranchIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string BranchName
        {
            get
            {
                return this.BranchNameField;
            }
            set
            {
                this.BranchNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> BusinessKey
        {
            get
            {
                return this.BusinessKeyField;
            }
            set
            {
                this.BusinessKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<short> ChannelId
        {
            get
            {
                return this.ChannelIdField;
            }
            set
            {
                this.ChannelIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Credit
        {
            get
            {
                return this.CreditField;
            }
            set
            {
                this.CreditField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal CurrentBalance
        {
            get
            {
                return this.CurrentBalanceField;
            }
            set
            {
                this.CurrentBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Debit
        {
            get
            {
                return this.DebitField;
            }
            set
            {
                this.DebitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte FEC
        {
            get
            {
                return this.FECField;
            }
            set
            {
                this.FECField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FECName
        {
            get
            {
                return this.FECNameField;
            }
            set
            {
                this.FECNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ReceiverIBAN
        {
            get
            {
                return this.ReceiverIBANField;
            }
            set
            {
                this.ReceiverIBANField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ResourceCode
        {
            get
            {
                return this.ResourceCodeField;
            }
            set
            {
                this.ResourceCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SenderIBAN
        {
            get
            {
                return this.SenderIBANField;
            }
            set
            {
                this.SenderIBANField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SenderIdentityNumber
        {
            get
            {
                return this.SenderIdentityNumberField;
            }
            set
            {
                this.SenderIdentityNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime SystemDate
        {
            get
            {
                return this.SystemDateField;
            }
            set
            {
                this.SystemDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime TranDate
        {
            get
            {
                return this.TranDateField;
            }
            set
            {
                this.TranDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TranRef
        {
            get
            {
                return this.TranRefField;
            }
            set
            {
                this.TranRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string TranType
        {
            get
            {
                return this.TranTypeField;
            }
            set
            {
                this.TranTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> ValueDate
        {
            get
            {
                return this.ValueDateField;
            }
            set
            {
                this.ValueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string VirtualIBAN
        {
            get
            {
                return this.VirtualIBANField;
            }
            set
            {
                this.VirtualIBANField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://boa.net/BOA.Integration.CoreBanking.Teller/Service", ConfigurationName="EmlakSrv.IAccountStatementService")]
    public interface IAccountStatementService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://boa.net/BOA.Integration.CoreBanking.Teller/Service/IAccountStatementServic" +
            "e/GetAccountStatement", ReplyAction="http://boa.net/BOA.Integration.CoreBanking.Teller/Service/IAccountStatementServic" +
            "e/GetAccountStatementResponse")]
        System.Threading.Tasks.Task<EmlakSrv.ResponseModelBaseOfArrayOfAccountContractNx15LZU3> GetAccountStatementAsync(EmlakSrv.AccountStatetmentRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IAccountStatementServiceChannel : EmlakSrv.IAccountStatementService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class AccountStatementServiceClient : System.ServiceModel.ClientBase<EmlakSrv.IAccountStatementService>, EmlakSrv.IAccountStatementService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AccountStatementServiceClient() : 
                base(AccountStatementServiceClient.GetDefaultBinding(), AccountStatementServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IAccountStatementService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountStatementServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(AccountStatementServiceClient.GetBindingForEndpoint(endpointConfiguration), AccountStatementServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountStatementServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AccountStatementServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountStatementServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AccountStatementServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccountStatementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<EmlakSrv.ResponseModelBaseOfArrayOfAccountContractNx15LZU3> GetAccountStatementAsync(EmlakSrv.AccountStatetmentRequest request)
        {
            return base.Channel.GetAccountStatementAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAccountStatementService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAccountStatementService))
            {
                return new System.ServiceModel.EndpointAddress("https://boa.emlakbank.com.tr/BOA.Integration.WCFService/BOA.Integration.AccountSt" +
                        "atement/AccountStatementService.svc/Basic");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AccountStatementServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IAccountStatementService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AccountStatementServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IAccountStatementService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IAccountStatementService,
        }
    }
}
