//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QNBSrv
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://teknikbaglantiekstre.genericekstrenew2.driver.maestro.ibtech.com")]
    public partial class TeknikBaglantiServiceException
    {
        
        private Exception teknikBaglantiServiceException1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TeknikBaglantiServiceException", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public Exception TeknikBaglantiServiceException1
        {
            get
            {
                return this.teknikBaglantiServiceException1Field;
            }
            set
            {
                this.teknikBaglantiServiceException1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://teknikbaglantiekstre.genericekstrenew2.driver.maestro.ibtech.com")]
    public partial class Exception
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getextendeddetailtransactioninfo.model.genericekstrenew2.driver.maestro.ib" +
        "tech.com/xsd")]
    public partial class ExtendedDetailTransactionInfo
    {
        
        private string currencyCodeField;
        
        private string ddFirmInvoiceNumberField;
        
        private string ddFirmReferenceNumberField;
        
        private string ddReferenceNumberField;
        
        private string debitOrCreditCodeField;
        
        private string eftInquiryNumberField;
        
        private string eftReturnDescriptionField;
        
        private string muhasebeFisNoField;
        
        private string operationNameField;
        
        private string opponentAccountNoField;
        
        private string opponentBankField;
        
        private string opponentBankCodeField;
        
        private string opponentBranchField;
        
        private string opponentBranchCodeField;
        
        private string opponentCityCodeField;
        
        private string opponentIBANField;
        
        private string opponentTAXNoPIDNoField;
        
        private string processCodeField;
        
        private long productOperationRefNoField;
        
        private bool productOperationRefNoFieldSpecified;
        
        private string reserveField1Field;
        
        private string reserveField2Field;
        
        private string reserveField3Field;
        
        private long statementTransactionOrderField;
        
        private bool statementTransactionOrderFieldSpecified;
        
        private System.Nullable<decimal> transactionAmountField;
        
        private bool transactionAmountFieldSpecified;
        
        private System.Nullable<decimal> transactionBalanceField;
        
        private bool transactionBalanceFieldSpecified;
        
        private System.Nullable<System.DateTime> transactionDateField;
        
        private bool transactionDateFieldSpecified;
        
        private string transactionDescriptionField;
        
        private System.Nullable<decimal> transactionExchangeRateField;
        
        private bool transactionExchangeRateFieldSpecified;
        
        private long transactionIdField;
        
        private bool transactionIdFieldSpecified;
        
        private System.Nullable<System.DateTime> valueDateField;
        
        private bool valueDateFieldSpecified;
        
        private string vheFirmDocumentNumberField;
        
        private string vheTrxDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string currencyCode
        {
            get
            {
                return this.currencyCodeField;
            }
            set
            {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string ddFirmInvoiceNumber
        {
            get
            {
                return this.ddFirmInvoiceNumberField;
            }
            set
            {
                this.ddFirmInvoiceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string ddFirmReferenceNumber
        {
            get
            {
                return this.ddFirmReferenceNumberField;
            }
            set
            {
                this.ddFirmReferenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string ddReferenceNumber
        {
            get
            {
                return this.ddReferenceNumberField;
            }
            set
            {
                this.ddReferenceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string debitOrCreditCode
        {
            get
            {
                return this.debitOrCreditCodeField;
            }
            set
            {
                this.debitOrCreditCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string eftInquiryNumber
        {
            get
            {
                return this.eftInquiryNumberField;
            }
            set
            {
                this.eftInquiryNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string eftReturnDescription
        {
            get
            {
                return this.eftReturnDescriptionField;
            }
            set
            {
                this.eftReturnDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string muhasebeFisNo
        {
            get
            {
                return this.muhasebeFisNoField;
            }
            set
            {
                this.muhasebeFisNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string operationName
        {
            get
            {
                return this.operationNameField;
            }
            set
            {
                this.operationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public string opponentAccountNo
        {
            get
            {
                return this.opponentAccountNoField;
            }
            set
            {
                this.opponentAccountNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public string opponentBank
        {
            get
            {
                return this.opponentBankField;
            }
            set
            {
                this.opponentBankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public string opponentBankCode
        {
            get
            {
                return this.opponentBankCodeField;
            }
            set
            {
                this.opponentBankCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public string opponentBranch
        {
            get
            {
                return this.opponentBranchField;
            }
            set
            {
                this.opponentBranchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string opponentBranchCode
        {
            get
            {
                return this.opponentBranchCodeField;
            }
            set
            {
                this.opponentBranchCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public string opponentCityCode
        {
            get
            {
                return this.opponentCityCodeField;
            }
            set
            {
                this.opponentCityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public string opponentIBAN
        {
            get
            {
                return this.opponentIBANField;
            }
            set
            {
                this.opponentIBANField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=16)]
        public string opponentTAXNoPIDNo
        {
            get
            {
                return this.opponentTAXNoPIDNoField;
            }
            set
            {
                this.opponentTAXNoPIDNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=17)]
        public string processCode
        {
            get
            {
                return this.processCodeField;
            }
            set
            {
                this.processCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public long productOperationRefNo
        {
            get
            {
                return this.productOperationRefNoField;
            }
            set
            {
                this.productOperationRefNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool productOperationRefNoSpecified
        {
            get
            {
                return this.productOperationRefNoFieldSpecified;
            }
            set
            {
                this.productOperationRefNoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=19)]
        public string reserveField1
        {
            get
            {
                return this.reserveField1Field;
            }
            set
            {
                this.reserveField1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=20)]
        public string reserveField2
        {
            get
            {
                return this.reserveField2Field;
            }
            set
            {
                this.reserveField2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=21)]
        public string reserveField3
        {
            get
            {
                return this.reserveField3Field;
            }
            set
            {
                this.reserveField3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public long statementTransactionOrder
        {
            get
            {
                return this.statementTransactionOrderField;
            }
            set
            {
                this.statementTransactionOrderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statementTransactionOrderSpecified
        {
            get
            {
                return this.statementTransactionOrderFieldSpecified;
            }
            set
            {
                this.statementTransactionOrderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=23)]
        public System.Nullable<decimal> transactionAmount
        {
            get
            {
                return this.transactionAmountField;
            }
            set
            {
                this.transactionAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transactionAmountSpecified
        {
            get
            {
                return this.transactionAmountFieldSpecified;
            }
            set
            {
                this.transactionAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=24)]
        public System.Nullable<decimal> transactionBalance
        {
            get
            {
                return this.transactionBalanceField;
            }
            set
            {
                this.transactionBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transactionBalanceSpecified
        {
            get
            {
                return this.transactionBalanceFieldSpecified;
            }
            set
            {
                this.transactionBalanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=25)]
        public System.Nullable<System.DateTime> transactionDate
        {
            get
            {
                return this.transactionDateField;
            }
            set
            {
                this.transactionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transactionDateSpecified
        {
            get
            {
                return this.transactionDateFieldSpecified;
            }
            set
            {
                this.transactionDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=26)]
        public string transactionDescription
        {
            get
            {
                return this.transactionDescriptionField;
            }
            set
            {
                this.transactionDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=27)]
        public System.Nullable<decimal> transactionExchangeRate
        {
            get
            {
                return this.transactionExchangeRateField;
            }
            set
            {
                this.transactionExchangeRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transactionExchangeRateSpecified
        {
            get
            {
                return this.transactionExchangeRateFieldSpecified;
            }
            set
            {
                this.transactionExchangeRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public long transactionId
        {
            get
            {
                return this.transactionIdField;
            }
            set
            {
                this.transactionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool transactionIdSpecified
        {
            get
            {
                return this.transactionIdFieldSpecified;
            }
            set
            {
                this.transactionIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=29)]
        public System.Nullable<System.DateTime> valueDate
        {
            get
            {
                return this.valueDateField;
            }
            set
            {
                this.valueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueDateSpecified
        {
            get
            {
                return this.valueDateFieldSpecified;
            }
            set
            {
                this.valueDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=30)]
        public string vheFirmDocumentNumber
        {
            get
            {
                return this.vheFirmDocumentNumberField;
            }
            set
            {
                this.vheFirmDocumentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=31)]
        public string vheTrxDescription
        {
            get
            {
                return this.vheTrxDescriptionField;
            }
            set
            {
                this.vheTrxDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getextendeddetailtransactioninfo.model.genericekstrenew2.driver.maestro.ib" +
        "tech.com/xsd")]
    public partial class ExtendedDetailAccountInfo
    {
        
        private System.Nullable<decimal> accountBalanceField;
        
        private bool accountBalanceFieldSpecified;
        
        private string accountCurrencyCodeField;
        
        private string accountNoField;
        
        private string accountTitleField;
        
        private string accountTypeField;
        
        private string branchCodeField;
        
        private string branchNameField;
        
        private string customerNoField;
        
        private string ibanField;
        
        private System.Nullable<decimal> lastTrxClosingBalanceField;
        
        private bool lastTrxClosingBalanceFieldSpecified;
        
        private System.Nullable<System.DateTime> lastTrxClosingProcessDateField;
        
        private bool lastTrxClosingProcessDateFieldSpecified;
        
        private System.Nullable<System.DateTime> lastTrxClosingProcessTimeField;
        
        private bool lastTrxClosingProcessTimeFieldSpecified;
        
        private System.Nullable<System.DateTime> lastTrxDateField;
        
        private bool lastTrxDateFieldSpecified;
        
        private string lastTrxDebitOrCreditCodeField;
        
        private System.Nullable<decimal> openingBalanceField;
        
        private bool openingBalanceFieldSpecified;
        
        private System.Nullable<System.DateTime> openingBalanceDateField;
        
        private bool openingBalanceDateFieldSpecified;
        
        private string previousTrxDebitOrCreditCodeField;
        
        private System.Nullable<decimal> previousTrxOpeningBalanceField;
        
        private bool previousTrxOpeningBalanceFieldSpecified;
        
        private System.Nullable<System.DateTime> previousTrxOpeningBalanceDateField;
        
        private bool previousTrxOpeningBalanceDateFieldSpecified;
        
        private string reserveField1Field;
        
        private string reserveField2Field;
        
        private string reserveField3Field;
        
        private ExtendedDetailTransactionInfo[] transactionsField;
        
        private System.Nullable<decimal> usableOVDPLimitField;
        
        private bool usableOVDPLimitFieldSpecified;
        
        private System.Nullable<decimal> usableTotalAmountField;
        
        private bool usableTotalAmountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<decimal> accountBalance
        {
            get
            {
                return this.accountBalanceField;
            }
            set
            {
                this.accountBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accountBalanceSpecified
        {
            get
            {
                return this.accountBalanceFieldSpecified;
            }
            set
            {
                this.accountBalanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string accountCurrencyCode
        {
            get
            {
                return this.accountCurrencyCodeField;
            }
            set
            {
                this.accountCurrencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string accountNo
        {
            get
            {
                return this.accountNoField;
            }
            set
            {
                this.accountNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string accountTitle
        {
            get
            {
                return this.accountTitleField;
            }
            set
            {
                this.accountTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string accountType
        {
            get
            {
                return this.accountTypeField;
            }
            set
            {
                this.accountTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string branchCode
        {
            get
            {
                return this.branchCodeField;
            }
            set
            {
                this.branchCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string branchName
        {
            get
            {
                return this.branchNameField;
            }
            set
            {
                this.branchNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string customerNo
        {
            get
            {
                return this.customerNoField;
            }
            set
            {
                this.customerNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=8)]
        public string iban
        {
            get
            {
                return this.ibanField;
            }
            set
            {
                this.ibanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public System.Nullable<decimal> lastTrxClosingBalance
        {
            get
            {
                return this.lastTrxClosingBalanceField;
            }
            set
            {
                this.lastTrxClosingBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastTrxClosingBalanceSpecified
        {
            get
            {
                return this.lastTrxClosingBalanceFieldSpecified;
            }
            set
            {
                this.lastTrxClosingBalanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public System.Nullable<System.DateTime> lastTrxClosingProcessDate
        {
            get
            {
                return this.lastTrxClosingProcessDateField;
            }
            set
            {
                this.lastTrxClosingProcessDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastTrxClosingProcessDateSpecified
        {
            get
            {
                return this.lastTrxClosingProcessDateFieldSpecified;
            }
            set
            {
                this.lastTrxClosingProcessDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public System.Nullable<System.DateTime> lastTrxClosingProcessTime
        {
            get
            {
                return this.lastTrxClosingProcessTimeField;
            }
            set
            {
                this.lastTrxClosingProcessTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastTrxClosingProcessTimeSpecified
        {
            get
            {
                return this.lastTrxClosingProcessTimeFieldSpecified;
            }
            set
            {
                this.lastTrxClosingProcessTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=12)]
        public System.Nullable<System.DateTime> lastTrxDate
        {
            get
            {
                return this.lastTrxDateField;
            }
            set
            {
                this.lastTrxDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastTrxDateSpecified
        {
            get
            {
                return this.lastTrxDateFieldSpecified;
            }
            set
            {
                this.lastTrxDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=13)]
        public string lastTrxDebitOrCreditCode
        {
            get
            {
                return this.lastTrxDebitOrCreditCodeField;
            }
            set
            {
                this.lastTrxDebitOrCreditCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=14)]
        public System.Nullable<decimal> openingBalance
        {
            get
            {
                return this.openingBalanceField;
            }
            set
            {
                this.openingBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool openingBalanceSpecified
        {
            get
            {
                return this.openingBalanceFieldSpecified;
            }
            set
            {
                this.openingBalanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=15)]
        public System.Nullable<System.DateTime> openingBalanceDate
        {
            get
            {
                return this.openingBalanceDateField;
            }
            set
            {
                this.openingBalanceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool openingBalanceDateSpecified
        {
            get
            {
                return this.openingBalanceDateFieldSpecified;
            }
            set
            {
                this.openingBalanceDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=16)]
        public string previousTrxDebitOrCreditCode
        {
            get
            {
                return this.previousTrxDebitOrCreditCodeField;
            }
            set
            {
                this.previousTrxDebitOrCreditCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=17)]
        public System.Nullable<decimal> previousTrxOpeningBalance
        {
            get
            {
                return this.previousTrxOpeningBalanceField;
            }
            set
            {
                this.previousTrxOpeningBalanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool previousTrxOpeningBalanceSpecified
        {
            get
            {
                return this.previousTrxOpeningBalanceFieldSpecified;
            }
            set
            {
                this.previousTrxOpeningBalanceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=18)]
        public System.Nullable<System.DateTime> previousTrxOpeningBalanceDate
        {
            get
            {
                return this.previousTrxOpeningBalanceDateField;
            }
            set
            {
                this.previousTrxOpeningBalanceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool previousTrxOpeningBalanceDateSpecified
        {
            get
            {
                return this.previousTrxOpeningBalanceDateFieldSpecified;
            }
            set
            {
                this.previousTrxOpeningBalanceDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=19)]
        public string reserveField1
        {
            get
            {
                return this.reserveField1Field;
            }
            set
            {
                this.reserveField1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=20)]
        public string reserveField2
        {
            get
            {
                return this.reserveField2Field;
            }
            set
            {
                this.reserveField2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=21)]
        public string reserveField3
        {
            get
            {
                return this.reserveField3Field;
            }
            set
            {
                this.reserveField3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("transactions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=22)]
        public ExtendedDetailTransactionInfo[] transactions
        {
            get
            {
                return this.transactionsField;
            }
            set
            {
                this.transactionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=23)]
        public System.Nullable<decimal> usableOVDPLimit
        {
            get
            {
                return this.usableOVDPLimitField;
            }
            set
            {
                this.usableOVDPLimitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usableOVDPLimitSpecified
        {
            get
            {
                return this.usableOVDPLimitFieldSpecified;
            }
            set
            {
                this.usableOVDPLimitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=24)]
        public System.Nullable<decimal> usableTotalAmount
        {
            get
            {
                return this.usableTotalAmountField;
            }
            set
            {
                this.usableTotalAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usableTotalAmountSpecified
        {
            get
            {
                return this.usableTotalAmountFieldSpecified;
            }
            set
            {
                this.usableTotalAmountFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getextendeddetailtransactioninfo.model.genericekstrenew2.driver.maestro.ib" +
        "tech.com/xsd")]
    public partial class GetExtendedDetailAccountInfoResponse
    {
        
        private ExtendedDetailAccountInfo[] accountInfoReturnTypeField;
        
        private string errorCodeField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("accountInfos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ExtendedDetailAccountInfo[] accountInfoReturnType
        {
            get
            {
                return this.accountInfoReturnTypeField;
            }
            set
            {
                this.accountInfoReturnTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string errorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string errorDescription
        {
            get
            {
                return this.errorDescriptionField;
            }
            set
            {
                this.errorDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getextendeddetailtransactioninfo.model.genericekstrenew2.driver.maestro.ib" +
        "tech.com/xsd")]
    public partial class GetExtendedDetailTransactionInfoInputType
    {
        
        private string accountNoField;
        
        private System.Nullable<System.DateTime> endDateField;
        
        private bool endDateFieldSpecified;
        
        private string ibanField;
        
        private System.Nullable<System.DateTime> startDateField;
        
        private bool startDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string accountNo
        {
            get
            {
                return this.accountNoField;
            }
            set
            {
                this.accountNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> endDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endDateSpecified
        {
            get
            {
                return this.endDateFieldSpecified;
            }
            set
            {
                this.endDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string iban
        {
            get
            {
                return this.ibanField;
            }
            set
            {
                this.ibanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> startDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startDateSpecified
        {
            get
            {
                return this.startDateFieldSpecified;
            }
            set
            {
                this.startDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getextendeddetailtransactioninfo.model.genericekstrenew2.driver.maestro.ib" +
        "tech.com/xsd")]
    public partial class GetExtendedDetailTransactionInfo
    {
        
        private string passwordField;
        
        private GetExtendedDetailTransactionInfoInputType transactionInfoInputTypeField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public GetExtendedDetailTransactionInfoInputType transactionInfoInputType
        {
            get
            {
                return this.transactionInfoInputTypeField;
            }
            set
            {
                this.transactionInfoInputTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://teknikbaglantiekstre.genericekstrenew2.driver.maestro.ibtech.com", ConfigurationName="QNBSrv.TeknikBaglantiServicePortType")]
    public interface TeknikBaglantiServicePortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:getTransactionInfo", ReplyAction="urn:getTransactionInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(QNBSrv.TeknikBaglantiServiceException), Action="urn:getTransactionInfoTeknikBaglantiServiceException", Name="TeknikBaglantiServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<QNBSrv.getTransactionInfoResponse> getTransactionInfoAsync(QNBSrv.getTransactionInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTransactionInfo", WrapperNamespace="http://teknikbaglantiekstre.genericekstrenew2.driver.maestro.ibtech.com", IsWrapped=true)]
    public partial class getTransactionInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://teknikbaglantiekstre.genericekstrenew2.driver.maestro.ibtech.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public QNBSrv.GetExtendedDetailTransactionInfo transactionInfo;
        
        public getTransactionInfoRequest()
        {
        }
        
        public getTransactionInfoRequest(QNBSrv.GetExtendedDetailTransactionInfo transactionInfo)
        {
            this.transactionInfo = transactionInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTransactionInfoResponse", WrapperNamespace="http://teknikbaglantiekstre.genericekstrenew2.driver.maestro.ibtech.com", IsWrapped=true)]
    public partial class getTransactionInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://teknikbaglantiekstre.genericekstrenew2.driver.maestro.ibtech.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public QNBSrv.GetExtendedDetailAccountInfoResponse @return;
        
        public getTransactionInfoResponse()
        {
        }
        
        public getTransactionInfoResponse(QNBSrv.GetExtendedDetailAccountInfoResponse @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface TeknikBaglantiServicePortTypeChannel : QNBSrv.TeknikBaglantiServicePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class TeknikBaglantiServicePortTypeClient : System.ServiceModel.ClientBase<QNBSrv.TeknikBaglantiServicePortType>, QNBSrv.TeknikBaglantiServicePortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TeknikBaglantiServicePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(TeknikBaglantiServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), TeknikBaglantiServicePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TeknikBaglantiServicePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TeknikBaglantiServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TeknikBaglantiServicePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TeknikBaglantiServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TeknikBaglantiServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<QNBSrv.getTransactionInfoResponse> QNBSrv.TeknikBaglantiServicePortType.getTransactionInfoAsync(QNBSrv.getTransactionInfoRequest request)
        {
            return base.Channel.getTransactionInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<QNBSrv.getTransactionInfoResponse> getTransactionInfoAsync(QNBSrv.GetExtendedDetailTransactionInfo transactionInfo)
        {
            QNBSrv.getTransactionInfoRequest inValue = new QNBSrv.getTransactionInfoRequest();
            inValue.transactionInfo = transactionInfo;
            return ((QNBSrv.TeknikBaglantiServicePortType)(this)).getTransactionInfoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TeknikBaglantiServiceHttpSoap11Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.TeknikBaglantiServiceHttpSoap12Endpoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TeknikBaglantiServiceHttpSoap11Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://fbmaestro.qnb.com.tr:9086/MaestroCoreEkstre/services/TeknikBaglantiService" +
                        ".TeknikBaglantiServiceHttpSoap11Endpoint/");
            }
            if ((endpointConfiguration == EndpointConfiguration.TeknikBaglantiServiceHttpSoap12Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://fbmaestro.qnb.com.tr:9086/MaestroCoreEkstre/services/TeknikBaglantiService" +
                        ".TeknikBaglantiServiceHttpSoap12Endpoint/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            TeknikBaglantiServiceHttpSoap11Endpoint,
            
            TeknikBaglantiServiceHttpSoap12Endpoint,
        }
    }
}
